src/containers/attributes/attributeEditor.jsx, src/pages/browser/Subsets.jsx, src/pages/settings/attributes.jsx, src/pages/settings/index.jsx, src/pages/settings/users/RenameUserDialog.jsx, src/pages/settings/users/SetPasswordDialog.jsx, src/pages/settings/users/index.jsx, src/pages/settings/users/userList.jsx, src/services/ayon.js, src/services/getAttributes.js, src/services/updateAttributes.js
Sort columns (default alphabetically) for pages **Browser**, **User** and **Attributes**.
- PascalCase file names.
- Breakout components into separate files.
- Use RTK Query for **Attributes** page.
=> Feature: Sortable Columns

src/app.jsx, src/context/websocketContext.jsx
Show restarting UI when server drops connection/restarting.
=> Fix: Websocket restarting

src/pages/settings/users/UserList.jsx, src/pages/settings/users/UserTile.jsx, src/pages/settings/users/UsersSettings.jsx, src/pages/settings/users/userDetail.jsx, src/services/user/getUsers.js
Fixes an issue where the users page could go into an infinite loop and crash the browser.
=> Fix Reformat User Detail Data Infinite Loop

src/components/EntityGridTile.jsx, src/containers/attributeTable.jsx, src/containers/header/projectMenu.jsx, src/containers/hierarchy.jsx, src/features/context.js, src/pages/editor/index.jsx, src/pages/project.jsx, src/pages/projectDashboard/panels/DashboardPanelWrapper.jsx, src/pages/projectDashboard/panels/HeartBeat.jsx, src/pages/projectDashboard/panels/ListStatsTile.jsx, src/pages/projectDashboard/panels/ProgressBar.jsx, src/pages/projectDashboard/panels/ProgressTile.jsx, src/pages/projectDashboard/panels/ProjectDetails.jsx, src/pages/projectDashboard/panels/ProjectHealth.jsx, src/pages/projectDashboard/panels/ProjectLatest.jsx, src/pages/projectDashboard/panels/ProjectStats.jsx, src/pages/projectDashboard/panels/ProjectTeams.jsx, src/pages/projectDashboard/panels/ProjectUsers.jsx, src/pages/projectDashboard/panels/Timeline.jsx, src/pages/settings/users/UserImage.jsx, src/pages/settings/users/UserImagesStacked.jsx, src/pages/settings/users/UserTile.jsx, src/services/ayon.js, src/services/getHierarchy.js
Implement teams and users panels endpoint and use consistent loading UX.
=> Chore: new project dashboard teams endpoint

src/pages/editor/editors.jsx, src/pages/editor/index.jsx, src/pages/editor/loader.js, src/pages/editor/queries.js, src/pages/editor/utils.jsx, src/services/ayon.js, src/services/editor/getEditor.js, src/services/editor/updateEditor.js
- Use RTK Query data fetching.
- Data is cached so moving around the app won't cause constant reloading.
- New/Updated data uses optimistic updates.
- You can now create child folders/tasks of newly created folders.
- Fixed a bug when trying to change the type.
=> Chore: project editor rtk query

.gitignore, src/components/DetailHeader.jsx, src/components/OverflowField.jsx, src/components/SearchDropdown.jsx, src/components/TableRow.jsx, src/components/dropdown.jsx, src/components/icons.jsx, src/components/status/statusField.jsx, src/components/status/statusSelect.jsx, src/containers/taskList.jsx, src/containers/thumbnail.jsx, src/features/editor.js, src/helpers/copyToClipboard.js, src/helpers/getFieldInObject.js, src/pages/editor/EditorPanel.jsx, src/pages/editor/StackedThumbnails.jsx, src/pages/editor/editors.jsx, src/pages/editor/fields/NameField.jsx, src/pages/editor/index.jsx, src/pages/editor/queries.js, src/pages/editor/utils.jsx, src/pages/projectDashboard/panels/DashboardPanelWrapper.jsx, src/services/editor/getEditor.js, src/services/editor/updateEditor.js, src/styles/index.scss, vite.config.js
Move from inline editing to side panel editing.
Editing
Editing Multiple
Creating New Nodes
Deleting
=> Feature: Project side panel editing

src/pages/event/EventPage.jsx, src/services/events/getEvents.js
- Event viewer always fetches new data on mount.
- Fixes and issue where old caches were being used.
- Moved pubsub to RTK Query
=> Fix: disable event viewer cache

src/pages/SettingsPage/Secrets.jsx
- Name pattern validation to prevent spaces.
- Catch server errors and show warning error message.
- Put in a scroll panel for when there are lots of secrets.
=> Secrets error handling and scroll

package.json, src/app.jsx, src/components/ErrorFallback.jsx
Wrap the app in an error boundary so that at least the user knows something has gone wrong when the app crashes.
- Doesn't catch errors in callbacks
Trying creating an error anywhere in the app.
=> React Error Boundary

src/components/User/UserDetailsHeader.jsx, src/containers/SessionList.jsx, src/containers/header/userMenu.jsx, src/pages/ProfilePage.jsx, src/pages/SettingsPage/UsersSettings/SetPasswordDialog.jsx, src/pages/SettingsPage/UsersSettings/userDetail.jsx, src/services/ayon.js, src/services/user/getUsers.js, src/services/user/updateUser.js
- Change layout to better match users page
- Use existing components from `UserDetails`
- Improve set password dialog
- Improve UserMenu design
- Profile page uses RTK Query
=> Enhancement: profile page improvements

src/containers/header/index.jsx, src/containers/header/projectMenu.jsx, src/containers/header/userMenu.jsx, src/containers/projectList.jsx, src/pages/EventsPage/EventDetail.jsx, src/pages/ProjectManagerPage/ProjectManagerPageContainer.jsx, src/styles/index.scss
- Double click on a project in project list to open it in the browser (only on project manager)
- Profile nav button
- Projects nav icon change and added the work "projects"
- User menu nav icon change
- Projects Manager nav icon change
=> Fix: double click open project and navbar

src/components/ContextMenuItem.jsx, src/pages/BrowserPage/Subsets.jsx, src/pages/EditorPage/EditorPage.jsx, src/pages/EditorPage/NewEntity.jsx
1. Right click on a folder in editor 
2. Select "Add Folder" or "Add Task"
3. Select different sub types
4. The name should match the sub type if the name hasn't already been set
=> Enhancement: creating new folders

src/pages/BrowserPage/RepresentationList.jsx
=> fix: Representation Table Header

src/containers/fieldFormat.jsx
=> fix: workfile detail path use overflow field

src/pages/BrowserPage/Products.jsx
=> fix: Show Columns matches column labels

src/app.jsx, src/components/GlobalContextMenu.jsx, src/containers/AddonList.jsx, src/containers/TeamList.jsx, src/containers/addonSettings/SettingsChangesTable.jsx, src/containers/hierarchy.jsx, src/containers/projectList.jsx, src/containers/taskList.jsx, src/context/contextMenuContext.jsx, src/hooks/useCreateContext.jsx, src/pages/BrowserPage/Products.jsx, src/pages/EditorPage/EditorPage.jsx, src/pages/ServicesPage/ServicesPage.jsx, src/pages/SettingsPage/AnatomyPresets/AnatomyPresets.jsx, src/pages/SettingsPage/AnatomyPresets/PresetList.jsx, src/pages/SettingsPage/Attributes.jsx, src/pages/SettingsPage/UsersSettings/UserList.jsx, src/pages/TeamsPage/UserListTeams.jsx
Instead of having lots of different context menus spread across different components this centralises and streamlines the dev experience. 
- Create global context menu.
- Fix issue where more than one context menu could be open.
- Improved the DX for creating new context menus.
- Context menus can be dynamic based on the data that was clicked on.
```javascript
// create model
const ctxMenuItems = [
{
label: 'Detail',
command: () => setShowDetail(true),
icon: 'database',
},
]
// useCreateContext hook provides context open function
const [ctxMenuShow] = useCreateContext(ctxMenuItems)
// use function in JSX (you need to provide the function with the event)
<div 
onContextMenu={ctxMenuShow}
/>
<TreeTable
onContextMenu={(e) => ctxMenuShow(e.originalEvent)}
/>
```
If you need to create menus …
=> Global context management

src/app.jsx, src/components/EntityGridTile.jsx, src/components/GlobalContextMenu.jsx, src/components/GridLayout.jsx, src/containers/AddonList.jsx, src/containers/TeamList.jsx, src/containers/addonSettings/SettingsChangesTable.jsx, src/containers/hierarchy.jsx, src/containers/projectList.jsx, src/containers/taskList.jsx, src/containers/thumbnail.jsx, src/context/contextMenuContext.jsx, src/features/context.js, src/hooks/useCreateContext.jsx, src/pages/BrowserPage/Products.jsx, src/pages/BrowserPage/ProductsGrid.jsx, src/pages/BrowserPage/ProductsList.jsx, src/pages/BrowserPage/ViewModeToggle.jsx, src/pages/EditorPage/EditorPage.jsx, src/pages/ProjectDashboard/panels/DashboardPanelWrapper.jsx, src/pages/ProjectDashboard/panels/ProjectLatest.jsx, src/pages/ProjectDashboard/panels/ProjectLatestRow.jsx, src/pages/ServicesPage/ServicesPage.jsx, src/pages/SettingsPage/AnatomyPresets/AnatomyPresets.jsx, src/pages/SettingsPage/AnatomyPresets/PresetList.jsx, src/pages/SettingsPage/Attributes.jsx, src/pages/SettingsPage/UsersSettings/UserList.jsx, src/pages/TeamsPage/UserListTeams.jsx, src/styles/getShimmerStyles.js
- Browser page show products as thumbnails in a grid
- Three new viewing modes "list (table)", "grid" and "grouped"
- Use skeleton loading shimmer
- "grouped" mode groups the products by productType (formally family)
- Multi-select supported
- Keyboard supported
=> Feature: Browser thumbnail view

src/pages/BrowserPage/Products.jsx, src/pages/BrowserPage/ProductsGrid.jsx
On a product grid tile...
- Show thumbnail for latest version
- Show status for latest version
=> fix: products grid thumbnail and status latest version

src/pages/BrowserPage/Products.jsx
Based on user research with @BigRoy 😎
=> Enhancement: hide column from context menu in products table

src/components/User/UserDetailsHeader.jsx, src/containers/TeamList.jsx, src/pages/ProjectAddon.jsx, src/pages/ProjectManagerPage/NewProjectDialog/NewProjectDialog.jsx, src/pages/ServicesPage/NewServiceDialog.jsx, src/pages/SettingsPage/AnatomyPresets/AnatomyPresets.jsx, src/pages/SettingsPage/Roles/rolesList.jsx, src/pages/SettingsPage/UsersSettings/RenameUserDialog.jsx, src/pages/SettingsPage/UsersSettings/SetPasswordDialog.jsx, src/pages/TeamsPage/CreateNewTeam.jsx, src/pages/TeamsPage/TeamsPage.jsx, src/pages/TeamsPage/UserListTeams.jsx
- add to selected teams or [team name] when singluar context menu
- fixed add/remove from team out of sync
- remove auto selection of all users when selecting a team
=> Enhancement: add to for selected team on right click

src/components/CollapseButton.jsx, src/containers/header/projectMenu.jsx, src/containers/projectList.jsx, src/pages/BrowserPage/Detail.jsx, src/pages/EditorPage/NewEntity.jsx, src/pages/ProjectManagerPage/ProjectManagerPageContainer.jsx, src/styles/index.scss
- set the `isCollapsible` prop to enable
- this will be mainly used in the artist dashboard.
=> Feature: collapsable projects menu

src/components/ApiKeyManager.jsx
- fix issue clicking on input would cause delete method.
- Show confirmation dialog before deleting.
- Slight UX improvements
=> fix: delete key confirmation

src/pages/SettingsPage/Bundles/BundleDepPackage.jsx, src/pages/SettingsPage/Bundles/BundleDeps.jsx, src/pages/SettingsPage/Bundles/BundleDepsPicker.jsx, src/pages/SettingsPage/Bundles/BundleDetail.jsx, src/pages/SettingsPage/Bundles/BundleList.jsx, src/pages/SettingsPage/Bundles/Bundles.jsx, src/pages/SettingsPage/Bundles/Bundles.styled.js, src/pages/SettingsPage/Bundles/NewBundle.jsx, src/services/bundles.js, src/services/dependencyPackages.js
- Optimistic updates for updating/deleting bundles for faster UI.
- Creating new bundle still awaits query for that little waiting feedback for users.
- Now you can select a Dep Package for a platform.
=> Enhancement: Bundle select platform Dep Package

package.json, src/components/InstallerUpload/InstallerUpload.jsx, src/pages/SettingsPage/Bundles/BundleList.jsx, src/pages/SettingsPage/Bundles/Bundles.jsx, src/services/bundles.js, src/services/installers.js
This is hopefully only a temporary solution and so the UI isn't the best.
=> feature: upload installers and dep packages

src/components/InstallerDownload/InstallerDownload.jsx, src/containers/header/index.jsx, src/containers/header/userMenu.jsx, src/pages/ProfilePage.jsx, src/services/auth/getAuth.js
One time navbar button. Once an installer is clicked then `installerDownloaded='true'` is set in local storage so that it doesn't show again.
- Always shown in user menu
- Logout button moved from profile to user menu
=> Install ayon launcher button

src/components/Menu/MenuComponents/Menu.jsx, src/components/Menu/MenuComponents/Menu.styled.js
=> enhancement: menu footer content copy

src/containers/rolesDropdown.jsx, src/pages/SettingsPage/UsersSettings/UserAccessForm.jsx, src/pages/SettingsPage/UsersSettings/UserList.jsx, src/pages/SettingsPage/UsersSettings/userDetail.jsx
- fix issue where users couldn't be selected in user settings
- clean up some other areas
- fix an issue where roles wouldn't be compared with initForm correctly
=> critical: user selection broken

src/components/Menu/Menus/AppMenu.jsx, src/services/onBoarding/onBoarding.js
=> enhancement: restart on boarding app menu button

src/pages/EditorPage/EditorPage.jsx
- Fix an issue where the context menu was using an old selection state.
- You can now add folders and tasks when a task is selected, it will add the new entity as a sibling of the task.
=> fix: editor context and adding new on tasks

src/components/ServerRestartBanner.jsx
=> fix: restart server typo

src/pages/ProjectManagerPage/NewProjectDialog/NewProjectDialog.jsx
- prevents creating a project without the name and code
- automatically adds _ when adding a space
- automatically generates a 4 character code based on the name
- code is still easily overwritten by the user
=> fix: auto create code and prevent create without

src/components/ErrorFallback.jsx
=> fix: reload on failed imported module

src/components/icons.jsx, src/pages/EditorPage/EditorPage.jsx, src/pages/EditorPage/EditorPanel.jsx, src/pages/EditorPage/NewEntity.jsx, src/pages/EditorPage/TypeEditor.jsx, src/pages/EditorPage/fields/NameField.jsx, src/pages/EditorPage/queries.js, src/styles/index.scss
- Editor panel allows setting label and disables setting name.
- Editor table name column shows a little label icon when showing the label (might need to rethink this one).
- New Entity dialog input is for label and then auto converts to snake case for name value.
=> Add entity labels to editor

package.json, src/components/NoEntityFound.jsx, src/containers/Breadcrumbs/Breadcrumbs.styled.js, src/containers/header/AppNavLinks.jsx, src/containers/taskList.jsx, src/pages/EditorPage/EditorPage.jsx, src/pages/EditorPage/EditorPanel.jsx, src/pages/WorkfilesPage/WorkfileList.jsx
- Upgrade a-r-c to fix tags select crash
- header font size 16px to 14px
- editor columns width default 140
- workfiles showing old items when switching
Thanks @BigRoy
=> Fix: Community Feedback Bug

src/components/TeamMembersStacked/TeamMembersStacked.jsx, src/pages/ProjectDashboard/panels/ProjectTeams.jsx
=> enhancement: Project Teams shows more info

src/components/Menu/MenuComponents/MenuList.jsx, src/components/Menu/Menus/AppMenu.jsx, src/components/ProjectButton/ProjectButton.jsx, src/components/ProjectButton/ProjectButton.styled.js, src/containers/ProjectMenu/projectMenu.jsx, src/containers/ProjectMenu/projectMenu.styled.js, src/containers/projectList.jsx, src/pages/ProjectManagerPage/NewProjectDialog/NewProject.jsx, src/pages/ProjectManagerPage/ProjectManagerPage.jsx, src/pages/ProjectManagerPage/ProjectManagerPageContainer.jsx
- Improved project menu
- Moved project settings to right app menu
- Remove create project
- Revert new project to old dialog
- Open project menu and select a project
- Open project menu and pin/unpin a project
- Open project menu and go to project settings
- Create new project button on Project Dashboard (All Projects) button
=> Enhancement: projects menu recent projects

src/components/icons.jsx, src/containers/hierarchy.jsx, src/containers/taskList.jsx, src/pages/BrowserPage/Products.jsx, src/pages/EditorPage/fields/NameField.jsx, src/pages/WorkfilesPage/WorkfileList.jsx
- remove label icon from editor
- now there is a tooltip with the name field
- if there's no label then name will be used
=> fix: text with icon tooltip uses name

package.json, src/components/SearchDropdown.jsx, src/pages/EditorPage/EditorPage.jsx, src/pages/EditorPage/NewEntity.jsx, src/pages/EditorPage/NewSequence.jsx
- perf: only expand first folder when adding to selection
- fix: preselect label after folder add
- enhancement: check names are unique before adding
- fix: filter matches lowerCase + search on typing stop
=> Editor: add folder tool fixes

src/pages/ServicesPage/ServicesPage.jsx
Display service status as a badge and instead of the last seen column, display a red badge if a worker is unresponsive for more than 30 seconds.
=> Service page UX improvements

src/pages/UserDashboardPage/UserDashboardTasks/UserTasksContainer.jsx, src/services/userDashboard/updateUserDashboard.js
- Fix an issue where moving multiple tasks at once would break optimistic updates.
- Type error fix
=> Artist Dashboard: Kanban fixes

src/containers/projectList.jsx
- Fix context menu in projects table to work with multi and single select
=> Projects Table: Fix cannot delete or open project

src/containers/projectList.jsx, src/pages/UserDashboardPage/UserDashboardNoProjects/UserDashboardNoProjects.jsx, src/pages/UserDashboardPage/UserDashboardNoProjects/UserDashboardNoProjects.styled.js
- When there are no projects the dashboard will show a button that opens the new project dialog form.
1. Have no projects or inside `UserDashboardPage:57` set if state to always `true`.
2. Click "Create first project" button.
3. New project dialog should open.
4. Creating new project should direct user to newly created project in project settings.
=> Artist Dashboard: No projects button opens project dialog

src/containers/ProjectMenu/projectMenu.jsx, src/containers/ProjectMenu/projectMenu.styled.js
- Looks better with darkened overlay
- Fixes an issue where iframes would prevent clicking outside to close
=> Project Menu: darkening overlay

src/pages/ServicesPage/ServicesPage.jsx
- Fix: services context menu out of sync with selection
1. Select a service.
2. Right click and different service and perform action.
3. Action should be performed on new right clicked service not the initial selection.
4. Select multiple services.
5. Right click on current selection and perform action.
6. Action should be performed on selected services.
=> Services: Fix services context menu out of sync with selection

src/containers/AddonSettings/AddonSettings.jsx, src/containers/AddonSettings/utils.js, src/containers/AnatomyEditor.jsx, src/containers/SettingsEditor/SettingsEditor.jsx, src/containers/SettingsEditor/fields.jsx, src/pages/SettingsPage/AnatomyPresets/AnatomyPresets.jsx
Copy paste is now available in anatomy presets.
All fields are now copyable, some restrictions for pasting were removed.
=> Settings clipboard support improvements

src/app.jsx, src/containers/AddonSettings/AddonSettings.jsx, src/containers/AnatomyEditor.jsx, src/context/pasteContext.jsx, src/pages/ProjectManagerPage/ProjectAnatomy.jsx, src/pages/SettingsPage/AnatomyPresets/AnatomyPresets.jsx
When clipboard API is not available, paste command now invokes a pop up dialog, where the user may paste the settings/part of anatomy instead.
=> Paste settings without Clipboard API support (fallback to paste dialog)

package.json, src/pages/EditorPage/EditorPage.jsx, src/pages/EditorPage/EditorPanel.jsx, src/pages/EditorPage/utils.jsx
- Implement new dropdown with "use inheritance" button.
- Improve set to inherit button for other fields.
- When setting to inherit table will display "(inherit)" for the field.
- When committing a new inherited value, children should now properly update as well.
https://github.com/ynput/ayon-frontend/assets/49156310/942bb2a2-e225-4f00-aed9-39c6ba83054f
=> Edit page null values and inheritence

src/pages/BrowserPage/Detail.jsx, src/pages/BrowserPage/Products.jsx, src/services/entity/updateEntity.js, src/services/updateProducts.js, src/services/userDashboard/updateUserDashboard.js
- Better handle when an operation has an error and undo any optimistic updates.
- Effects: Browser, Editor and User Dashboard Kanban
=> Fix: Entity update error handling

src/pages/EditorPage/EditorPage.jsx, src/pages/EditorPage/EditorPanel.jsx, src/pages/EditorPage/utils.jsx, src/styles/index.scss
- Assignees column inside editor. 
- Maybe in the future you will be able to edit it inline.
=> enhancement: assignees column

src/components/MarketAddonCard/MarketAddonCard.jsx, src/components/MarketAddonCard/MarketAddonCard.styled.js, src/pages/MarketPage/AddonDetails/AddonDetails.jsx, src/pages/MarketPage/MarketAddonsList.jsx, src/pages/MarketPage/MarketPage.jsx
- Update all addons with one button!
- Fix: updating an addon now shows 'Updating' instead of 'Installing' (they are the same thing though)
=> enhancement: update all addons button

src/pages/EventsPage/EventDetail.jsx
Fix: broken project settings link
Fix: tooltips on buttons
Fix: remove broken link to browser
=> Events details panels fixes

src/components/status/statusField.jsx, src/components/status/statusSelect.jsx
Added chevron and hover effect for StatusSelect
=> fix: added chevron and hover effect on StatusSelect

.husky/pre-commit, src/pages/EditorPage/EditorPage.jsx
Remove deselection handler when clicking outside of table.
=> Fix: editor table removes selection on click outside

package.json, src/pages/BrowserPage/Detail.jsx, src/pages/EditorPage/EditorPanel.jsx
- Fixes sorting in assignee select and fixes #325.
- Improves dropdown searching.
- Fixes issue where dropdown would be behind a modal.
- Fixes an issue with tags not showing mixed values.
(Before **Alpha Go** would have been at the top because it includes `l` and is first alphabetically)
=> Fix Assignee Select and Tags Select

src/containers/header/AppHeader.jsx, src/containers/header/HeaderButton.jsx
- **Dashboard** renamed to **Home** to better reflect pages description.
- **Home** button moved to far left to better align with web standards.
- Use classnames for button booleans instead of styled components variables.
=> Dashboard renamed to Home

package.json
- increased version of ayon-react-components in package.json (Dialog component added in ayon-react-components)
=> Updated version of ARC in package json

src/containers/SettingsEditor/fields.jsx, src/containers/SettingsEditor/widgets.jsx
- **added non-null default to inputnumber**
- **use generic enum as the arrayitem key**
=> Settings editor floods log with errors

src/pages/EditorPage/EditorPage.jsx, src/pages/EditorPage/utils.jsx, src/pages/EditorPage/utils.styled.js
- Added new Status column
- Values in column change color when they are updated in Editor Panel on the right
- Status column can be filtered out by "Show columns" dropdown at the top
Demo:
https://github.com/ynput/ayon-frontend/assets/16327908/8112602a-9189-4615-963b-f16f8ec118bf
=> fix: Added new 'Status' column in EditorPage

src/pages/SettingsPage/AccessGroups/NewAccessGroup.jsx
- added access group dialog submitting form on hotkey shortcut -> ctrl/meta  + enter
=> fix: Added submit on ctrl/meta  + enter to access group dialog

src/components/MarketAddonCard/MarketAddonCard.jsx, src/context/restartContext.jsx, src/hooks/Tooltip/useTooltip.jsx, src/pages/MarketPage/AddonDetails/AddonDetails.jsx, src/pages/MarketPage/AddonDetails/AddonDetails.styled.js, src/pages/MarketPage/AddonDetails/useInstall.js, src/pages/MarketPage/MarketPage.jsx, src/services/addons/updateAddons.js
When an addons fails to download from the market it shows an error message.
https://github.com/ynput/ayon-frontend/assets/49156310/e34f4e5b-722e-4bb2-9567-a0df6388d829
=> Enhancement: 362 updating addons from marketplace does not handle errors

package.json, src/components/Actions/Actions.jsx, src/components/CommentInput/CommentInput.jsx, src/components/CommentInput/CommentInput.styled.js, src/components/Feed/ActivityComment/ActivityComment.jsx, src/components/Feed/ActivityComment/ActivityComment.styled.js, src/components/Feed/ActivityComment/activityMarkdownComponents.jsx, src/components/Feed/ActivityHeader/ActivityHeader.styled.js, src/components/Feed/ActivityItem.jsx, src/containers/Feed/Feed.jsx, src/containers/Feed/Feed.styled.js, src/containers/Feed/hooks/useCommentMutations.js, src/containers/Feed/hooks/useSaveScrollPos.js, src/containers/Feed/hooks/useTransformActivities.js, src/containers/FileUploadPreview/FileUploadPreview.jsx, src/containers/ThumbnailSimple.jsx, src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardDetails/UserDashboardDetails.jsx, src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardSlideOut/UserDashboardSlideOut.jsx, src/pages/UserDashboardPage/UserDashboardTasks/UserTasksContainer.jsx, src/pages/UserDashboardPage/util/usePrefetchTask.js, src/services/userDashboard/getUserDashboard.js, src/services/userDashboard/userDashboardQueries.js
Loads of bug fixes for the activity feed.
=> Activity feed: dev fixes

src/components/CommentInput/CommentInput.styled.js
=> fix(comment): checklists cursor misaligned

src/pages/EditorPage/EditorPage.jsx
-   [ ] When creating a new folder/task a field that has inherit=false should not be inherited on new entity.
https://github.com/ynput/ayon-frontend/assets/49156310/4e16840f-baf7-4439-9589-d1cd38623455
=> Editor: ensure attrib fields with inherit=false are not inherited

src/pages/SettingsPage/AddonInstall/AddonUpload.jsx
- fixed issue with displaying error for Upload Launcher dialog
https://github.com/ynput/ayon-frontend/assets/16327908/f2c3df29-9cd4-49c8-b823-ffead8c1ed5a
=> fix(upload): fix displaying error messages for addon upload

src/components/Feed/ActivityDate.jsx, src/components/Feed/ActivityVersions/ActivityVersions.jsx, src/components/Feed/ActivityVersions/ActivityVersions.styled.js, src/containers/Feed/Feed.jsx, src/containers/Feed/helpers/groupActivityVersions.js, src/containers/Feed/helpers/groupMinorActivities.js, src/containers/Feed/helpers/mergeSimilarActivities.js, src/containers/Feed/hooks/useTransformActivities.js
- Hover over any version to see it's createdAt date.
- Versions are now grouped within 5 minutes windows instead of 30 mins.
https://github.com/ynput/ayon-frontend/assets/49156310/c4bc2706-3d58-45f0-8817-99b16b1c807e
=> Feed: Version activities show date and small grouping window

src/components/ThumbnailUploader/ThumbnailUploader.jsx, src/components/ThumbnailUploader/ThumbnailUploader.styled.js, src/containers/thumbnail.jsx, src/features/editor.js, src/pages/EditorPage/EditorPage.jsx
Dragging a value inside of the editor panel should not show the file upload dropzone.
Select some text in the editor panel and drag it, nothing should happen.
=> Editor: Editor dragging a value does not trigger thumbnail upload

src/components/ContextMenu/ContextMenu.scss, src/components/ContextMenu/ContextMenuItem.jsx, src/components/Menu/MenuComponents/Menu.styled.js, src/components/Menu/MenuComponents/MenuItem.jsx, src/components/ShortcutWidget/ShortcutWidget.jsx, src/hooks/Tooltip/Tooltip.styled.js, src/hooks/Tooltip/useTooltip.jsx, src/hooks/useCreateContext.jsx, src/pages/EditorPage/EditorPage.jsx, src/pages/SettingsPage/Bundles/BundleList.jsx, src/styles/index.scss
- Show shortcuts for actions in the context menu.
=> Shortcuts: show shortcuts more in context menus

src/components/Feed/ActivityVersions/ActivityVersions.jsx, src/components/ShortcutWidget/ShortcutWidget.jsx, src/components/VersionSelectorTool/PreviewVersionDropdown/PreviewVersionDropdown.jsx, src/components/VersionSelectorTool/PreviewVersionDropdown/PreviewVersionDropdown.styled.js, src/components/VersionSelectorTool/VersionSelectorTool.jsx, src/components/VersionSelectorTool/VersionSelectorTool.styled.js, src/components/VersionSelectorTool/hooks/usePreviewShortcuts.jsx, src/containers/Preview/Preview.jsx, src/containers/Preview/Preview.styled.js, src/containers/Preview/PreviewDialog.jsx, src/features/preview.js, src/pages/SettingsPage/Bundles/Bundles.jsx, src/services/preview/getPreview.js, src/services/preview/perviewQueries.js
Switch between versions seamlessly with helper buttons and shortcuts.
- `Z` - Preview version
- `X` - Open versions (all) selector 
- `C` - Next version
- `V` - Latest version
- `B` - Latest approved version
- `N` - Latest HERO version (if any)
https://github.com/ynput/ayon-frontend/assets/49156310/a35fec79-0b8f-4092-8851-af48764c0be1
=> Web Preview: Versions selector

src/components/VersionSelectorTool/VersionSelectorTool.jsx, src/containers/Preview/Preview.jsx, src/containers/Preview/Preview.styled.js, src/containers/Preview/PreviewDetailsPanel.jsx, src/containers/Preview/PreviewDialog.jsx, src/containers/Preview/PreviewPlayer.jsx, src/context/shortcutsContext.jsx, src/features/details.js
Show the selected versions details and feed.
Do we need the filters on here?
=> Web Preview: Version details panel and feed

src/components/Feed/ActivityItem.jsx, src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.styled.js
- Tags and Assignee select max width
- Created at tag in feed wraps now
=> Details: multi selection could cause overflows

src/pages/BrowserPage/Products/NoProducts.jsx, src/pages/BrowserPage/Products/Products.jsx, src/services/product/getProduct.js
If there is an error getting the products list, show an error message to the user.
This _**should**_ never happen.
=> fix(browser): Show error message on products error

src/components/CommentMentionSelect/CommentMentionSelect.jsx, src/components/CommentMentionSelect/CommentMentionSelect.styled.js, src/components/Feed/ActivityDate.jsx, src/containers/Feed/mentionHelpers/getMentionOptions.js, src/containers/Feed/mentionHelpers/getMentionTasks.js, src/containers/Feed/mentionHelpers/getMentionVersions.js, src/pages/BrowserPage/BrowserDetailsPanel.jsx, src/services/activities/activityQueries.js
When mentioning something improve the information provided in the suggestions.
- Order versions by `createdAt` with most recent at the top.
- Always show the products name prefix and timestamp suffix for versions.
- Show the product type icon for versions.
- Always show the folder name prefix for tasks.
- Fix task icons not showing in project context.
- Show a header that displays what thing you are currently searching for (users, versions, tasks).
https://github.com/ynput/ayon-frontend/assets/49156310/2e9e75be-e136-4a0e-af90-c29320713466
=> Activity Feed: Improve mention suggestions

src/services/userDashboard/userDashboardHelpers.js, src/services/userDashboard/userDashboardQueries.js
If a task does not have a thumbnail then we should use the latest version thumbnail.
=> Dashboard: Tasks should use latest version thumbnail if no task thumbnailId

package.json, src/components/ListItem/ListItem.jsx, src/components/ListItem/ListItem.styled.js, src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.jsx, src/pages/EditorPage/EditorPanel.jsx, src/pages/EditorPage/utils.jsx, src/pages/TeamsPage/CreateNewTeam/CreateNewTeam.jsx
Align assignees left in editor column.
Add empty placeholder message
Add tooltip to help distinguish between "Author" and "Assignee Users".
=> Editor: Assignee column align left

src/containers/AddonSettings/AddonSettings.jsx, src/containers/AddonSettings/CopyBundleSettingsButton.jsx, src/containers/AddonSettings/SettingsChangesTable.jsx, src/containers/AddonSettings/VariantSelector.jsx, src/containers/CopySettings/CopySettingsDialog.jsx, src/containers/CopySettings/CopySettingsNode.jsx, src/containers/CopySettings/CopySettingsNode.styled.jsx
Copy settings function should now provide 1:1 copy of the source settings (including copying "unpins"). 
List of changes now highlights overridden values and excludes fields with no changes on the same override level.
=> Settings: improved change list in copy settings dialog

src/components/AttribForm/AttribForm.jsx, src/components/FolderSequence/FolderSequence.jsx, src/components/SearchDropdown.jsx, src/components/status/statusField.jsx, src/containers/AddonList.jsx, src/containers/SettingsEditor/fields.jsx, src/context/pasteContext.jsx, src/pages/EditorPage/EditorPage.jsx, src/pages/OnBoarding/util/OnBoardingContext.jsx, src/pages/ProjectPage.jsx, src/pages/SettingsPage/AddonInstall/AddonUpload.jsx, src/pages/SettingsPage/Bundles/NewBundle.jsx, src/pages/SettingsPage/UsersSettings/UserList.jsx, src/pages/SettingsPage/UsersSettings/newUser.jsx, src/pages/TeamsPage/TeamsPage.jsx
Luke forced me to make a PR to front-end just so I'm not only friends with @martastain's backend.
-   [x] Commit contains changes that are not only whitespaces
-   [x] Luke is happy
This PR may affect the user, positively.
Future you will be happy with less typos - especially when they only fix comments it's basically a party-starter. 🥳 
The paste field now correctly spells the word "browser" which is an amazing achievement considering Today's technological standards.
=> Chore: Fix typos

package.json, src/components/MeOrUserSwitch/MeOrUserSwitch.jsx, src/components/MeOrUserSwitch/MeOrUserSwitch.styled.js, src/features/dashboard.js, src/pages/UserDashboardPage/UserDashboardTasks/DashboardTasksToolbar/DashboardTasksToolbar.jsx, src/pages/UserDashboardPage/UserDashboardTasks/UserTasksContainer.jsx
- Select/deselect all users
- This will show all tasks that have any user assigned
- Showing all tasks regardless of assignee is out the scope of this PR but lays the groundwork for it
=> Tasks: Show all tasks and select all users

src/hooks/usePatchProductsListWithVersions.js, src/pages/UserDashboardPage/UserDashboardTasks/KanBanColumn/KanBanColumn.styled.js, src/services/entity/updateEntity.js
- The version status wouldn't update properly
- Column headers could become hidden when there were too many tasks
- Fixes another issue that mean the details panel wasn't getting it's data patched correctly.
=> Details Panel: changing version status broken inside dashboard

src/containers/ProjectMenu/projectMenu.jsx, src/services/user/updateUser.js
Now your pinned projects will be synced across all devices you are logged into.
- Pinning projects updates `frontendPreferences` on user data row.
- Legacy pinned projects are migrated to new system when the user makes any changes to pinned.
=> Project menu: sync pinned projects across users devices 

src/components/CollapseButton.jsx, src/containers/ProjectMenu/projectMenu.jsx, src/containers/projectList.jsx, src/styles/index.scss
- Pinned projects will be sorted to the top and have a pin icon.
- Right click on a project/s to pin/unpin.
https://github.com/ynput/ayon-frontend/assets/49156310/9dd1e7a2-cbf2-4d33-9e7f-12beb0427f98
=> Projects: show and manage pinned projects in main projects list

src/pages/LoginPage/LoginPage.jsx
-   [ ] This comment contains a description of changes
-   [ ] Referenced issue is linked
Applied validations on login form - username and password, so we will not make unnecessary api call to backend when user has not entered username and password
Videos attached for issue and after resolving it.
https://github.com/ynput/ayon-frontend/assets/169469158/469db9a2-2b15-4fb4-bbb3-e99a43b017a9
https://github.com/ynput/ayon-frontend/assets/169469158/45156ecc-14ef-4cbc-8c02-b64f29782fb0
=> Applied the validations on login username and password

src/components/CommentInput/CommentInput.styled.js, src/components/CommentInput/InputMarkdownConvert.jsx, src/components/CommentInput/quillToMarkdown.jsx, src/components/Feed/ActivityCheckbox/ActivityCheckbox.styled.js, src/components/Feed/ActivityComment/ActivityComment.jsx, src/components/Feed/ActivityComment/ActivityComment.styled.js, src/components/Feed/ActivityComment/activityMarkdownComponents.jsx, src/components/Feed/ActivityReferenceTooltip/ActivityReferenceTooltip.jsx
=> Comment: many bug fixes

src/containers/VideoPlayer/Timecode.jsx, src/containers/VideoPlayer/VideoPlayerControls.jsx
Position display now uses 1-indexed value
=> Position indicator starts with one instead of zero

src/components/ReviewablesSelector/ReviewablesSelector.tsx, src/components/VersionSelectorTool/ReviewVersionDropdown/ReviewVersionDropdown.jsx, src/components/VersionSelectorTool/ReviewVersionDropdown/ReviewVersionDropdown.styled.js, src/components/VersionSelectorTool/VersionSelectorTool.jsx, src/components/VersionSelectorTool/VersionSelectorTool.styled.js, src/containers/Viewer/Viewer.styled.ts, src/containers/Viewer/Viewer.tsx, src/containers/Viewer/ViewerDialog.tsx, src/features/viewer.js, src/pages/BrowserPage/Products/Products.jsx
When multiple products are available for review (folder or task opened), display a dropdown menu to select the product you want to view.
https://github.com/user-attachments/assets/8c2cba51-15c3-4005-9700-4ab377042870
=> Viewer: Products select

src/components/Menu/Menus/AppMenu.jsx
=> AppMenu: removed market entry for managers

src/components/ContextMenu/ContextMenu.scss, src/hooks/Tooltip/Tooltip.styled.js
=> Tooltips: Should not appear in front of context menu

package.json, src/components/VersionSelectorTool/ReviewVersionDropdown/ReviewVersionDropdown.jsx
- Show an error when a value is missing in a dropdown.
- Dropdown now auto scrolls to selected item
=> Dropdown: Show warning on invalid items

src/components/InfoMessage/InfoMessage.styled.ts, src/components/InfoMessage/InfoMessage.tsx, src/components/InfoMessage/index.ts, src/pages/SettingsPage/UsersSettings/RenameUserDialog.tsx
You really don't want to rename a user.
Created new component `InfoMessage`.
1. `/settings/users`.
2. Click user.
3. Click on username to rename.
=> Users: Warn when renaming user

src/helpers/checkName.js
Ensure that capital letters are preserved when parsing label to name.
- Removes leading and trials all special characters
- Replaces all special characters with `_`
=> Editor: Naming consistency

src/api/rest.ts, src/components/ReviewableCard/ReviewableCard.styled.ts, src/components/ReviewableCard/ReviewableCard.tsx, src/containers/Actions/Actions.jsx, src/containers/ReviewablesList/EditReviewableDialog.tsx, src/containers/ReviewablesList/ReviewablesList.styled.ts, src/containers/ReviewablesList/ReviewablesList.tsx, src/containers/ReviewablesList/SortableReviewableCard.tsx, src/services/review/getReview.ts, src/services/review/updateReview.ts
- Reorder reviewables
- Edit reviewable label
1. [http://localhost:3000/projects/AY_CG_demo/browser?viewer_product=67489e2cf4d25d0d9dee3946063f7310&viewer_version=7265419a231f11ef9f4414ac6003f3c1&project_name=AY_CG_demo&reviewable_id=6bb17043c188515ea10f96bbf90623d0](http://localhost:3000/projects/AY_CG_demo/browser?viewer_product=67489e2cf4d25d0d9dee3946063f7310&viewer_version=7265419a231f11ef9f4414ac6003f3c1&project_name=AY_CG_demo&reviewable_id=6bb17043c188515ea10f96bbf90623d0)
2. Drag to sort reviewables
3. Click on edit button to update a label
https://github.com/user-attachments/assets/7bb6a5f0-f164-40e6-b8ba-8f158398a633
=> Reviewables: Reorder and rename reviewables

src/helpers/routes.ts, src/pages/UserDashboardPage/UserDashboardTasks/KanBanColumn/KanBanColumn.jsx, src/pages/UserDashboardPage/UserDashboardTasks/ListGroup/ListGroup.jsx, src/pages/UserDashboardPage/hooks/useGetTaskContextMenu.js
Handling double click event on Kanban tasks, navigating to browser page for said task.
#closes 600
=> Enhancement: Navigate to browser page on Dashboard task card double click

src/pages/SettingsPage/AddonsManager/AddonsManager.jsx, src/pages/SettingsPage/AddonsManager/AddonsManagerTable.jsx, src/pages/SettingsPage/AddonsManager/helpers.js, src/pages/SettingsPage/AddonsManager/useGetTableData.js
Using semver comparison algorithm when sorting addons by version in settings -> addons -> version panel
closes #599
=> fix(addons): Sorting addon versions using semver library algorithm

src/containers/SettingsEditor/widgets.jsx
It is now possible to comfortably edit numeric values in settings (negative numbers and decimals)
=> Settings: numeric inputs for decimal and negative numbers

src/containers/AddonSettings/AddonSettings.jsx, src/containers/AddonSettings/SettingsChangesTable.jsx, src/containers/SettingsEditor/SettingsEditor.jsx, src/pages/SettingsPage/SettingsAddon.jsx
Clicking to a staged change in the right-side panel in settings now brings you to the changed field.
https://github.com/user-attachments/assets/1544e067-7143-4867-8bdc-2ac8c6d7ca71
=> Settings: scroll to staged value

src/components/CommentInput/CommentInput.jsx, src/components/EntityPath/EntityPath.styled.ts, src/components/EntityPath/EntityPath.tsx, src/containers/DetailsPanel/DetailsPanel.jsx, src/containers/DetailsPanel/helpers/getEntityPathData.ts, src/containers/Feed/Feed.jsx, src/containers/Feed/hooks/useCommentMutations.js, src/pages/InboxPage/hooks/useGroupMessages.js, src/services/userDashboard/userDashboardHelpers.js
- Entity path loading shimmer styles
- Entity panel could sometimes be undefined
- New WS messages in inbox while selecting entity fixes
- Better async handling for new comments
=> Inbox and Feed fixes

src/pages/ProjectAddon.jsx
Allow an addon to select a folder from the project hierarchy. It returns the folder id.
`window.parent.modalRequest("folderPicker", (id) => callback(id));`
=> Addon: Folder Picker

src/components/Feed/ActivityAssigneeChange/ActivityAssigneeChange.styled.js, src/containers/Feed/Feed.jsx, src/containers/Feed/helpers/groupMinorActivities.js, src/containers/Feed/hooks/useTransformActivities.js
Merging multiple add/remove changes in activity timeline into 1 entry when the user/action is the same
https://github.com/user-attachments/assets/76d91bbe-4d6d-440d-8742-55d53530e1df
Closes #652
=> Activities: collapsing add/remove activities for same user

src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardList/UserDashboardList.jsx
Remove empty groups when grouping by field type.
=> Tasks List: Do not show empty groups in listview

gen/graphql.schema.json, package.json, src/api/graphql.ts, src/api/rest.ts, src/components/Feed/ActivityVersions/ActivityVersions.jsx, src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.jsx, src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.styled.js, src/pages/BrowserPage/Products/ProductsGrid.jsx, src/pages/UserDashboardPage/UserDashboardTasks/KanBanCard/KanBanCard.jsx, src/services/product/getProduct.js, src/services/userDashboard/gql/KanbanFragment.graphql, src/services/userDashboard/userDashboardHelpers.js, src/services/userDashboard/userDashboardQueries.js
Show a little play icon when some entity has a reviewable to watch.
1. Kanban card
2. Entity Details panel
3. Browser card
1. `yarn install`
2. Upload a reviewable for a version
3. Check that the play icon appears in the three locations above 
4. Check the folder of the version shows the icon in the details panel.
=> Reviewables: Show play icon when entity has a reviewable

src/pages/ProjectManagerPage/NewProjectDialog/AnatomyPresetDropdown.jsx, src/pages/SettingsPage/AnatomyPresets/AnatomyPresets.jsx, src/pages/SettingsPage/AnatomyPresets/PresetList.jsx
- Remove button at the top.
- Add "built in" table row at the top of the table.
- Other small fixes
https://github.com/user-attachments/assets/9db0cdc5-eab3-4c40-b3a6-40ae5b3548ab
=> Anatomy Presets: Rework primary and default

src/pages/MarketPage/AddonDetails/AddonDetails.jsx, src/pages/MarketPage/AddonDetails/AddonDetails.styled.js
Using links instead of buttons on Addon Market external links card
https://github.com/user-attachments/assets/f69493f5-ea44-4ec3-a268-31827a00cd2f
Closes #709
=> fix(addons) Using a link instead of button for external links section

src/containers/CopySettings/CopySettingsNode.jsx
As part of the ongoing efforts to maintain code accuracy and reflect real-world parameters, this PR updates the self-referential age-related comment. The relative temporal offset from the inception date has been adjusted to mirror the current chronological state.
- Modified the age comment to accurately represent the present age.
- Enhanced the integrity of developer commentary for future reference.
This change ensures that our codebase remains a true reflection of its maintainers' life stages, fostering an environment of transparency and honesty.
- Review the updated comment for correct age representation.
- Ensure all relevant documentation reflects this milestone appropriately.
=> Refactor temporal milestone declaration

src/pages/UserDashboardPage/util/getFilteredTasks.js
Allowing task filtering by assignee also. Using User name/Full name when filtering
https://github.com/user-attachments/assets/31962969-063f-4e51-bda1-c3d3ca38160d
Closes #720
=> fix(tasks): Allowing task filtering by user assignee name/full name also

src/components/CommentInput/CommentInput.jsx, src/components/Feed/ActivityComment/ActivityComment.jsx, src/containers/Feed/Feed.jsx, src/containers/Feed/hooks/useCommentMutations.js, src/services/activities/updateActivities.js
Removes a broken block of code that was causing issues with new comments disappearing.
Not totally sure why it was happening but everything is still working with it removed.
- Write a new comment
- Edit a comment
- Delete a comment
- Write a new comment with a checklist item.
- Checklists filter should also update.
- Update and delete should also change checklists filter.
- Open another version in the slide out.
- Now reference that version in a comment
- Should appear in the main feed and the slide out feed.
- update / delete and should also update in the slide out.
=> Feed: new comments disappearing

src/containers/ProjectMenu/projectMenu.jsx, src/containers/projectList.jsx
Navigation was broken due to missing dispatch call pattern
https://github.com/user-attachments/assets/7e8f8e65-4f81-4edc-8a25-4dc7e1bf178d
Closes #771
=> Context Menu: Manage project actions are not working

src/containers/DetailsPanel/DetailsPanel.jsx, src/containers/Watchers/Watchers.tsx, src/pages/InboxPage/InboxDetailsPanel.jsx
Whenever the user adds himself  to the watchers list checking his Inbox, a toast will be shown with the following message: 
'Future messages for {entity} will go to important.'
https://github.com/user-attachments/assets/13fe6d74-af14-4c0f-bb96-a2025fcdb078
Closes #717
=> Inbox: Toast notification when users add themselves as watchers

src/containers/Breadcrumbs/Breadcrumbs.styled.js, src/containers/header/AppHeader.jsx
Changed app header styling, breadcrumb is no longer absolute, adapts to the available space for smaller screens/resized windows 
https://github.com/user-attachments/assets/d84caf1d-b4ed-455c-8f0c-5aaaa9d58dfb
Closes #780
=> Breadcrumbs: Breadcrumb component adapts to available space to avoid overlapping

src/components/EntityThumbnailUploader/EntityThumbnailUploader.styled.tsx, src/components/EntityThumbnailUploader/EntityThumbnailUploader.tsx, src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.styled.js
Scrolling and header/form gap was lost due to element nesting changes, applied the required styling to fix both issues.
https://github.com/user-attachments/assets/eacd9e38-88ae-41ee-94fb-e59a832d3d53
Closes #792
=> Editor: Scrolling not working & details/form gap missing in details panel

src/features/middleware/searchParamsMiddleware.js
Removed unnecessary encoding.
https://github.com/user-attachments/assets/0cc199bc-2a5d-4623-9274-b21820f8e36a
Closes #799
=> URI: Removed extra url encoding when synching URI with url param

src/containers/ReviewablesList/ReviewablesList.styled.ts, src/containers/ReviewablesList/ReviewablesList.tsx, src/containers/ReviewablesList/ReviewablesUpload.styled.tsx, src/containers/ReviewablesList/ReviewablesUpload.tsx, src/containers/Viewer/Viewer.styled.ts, src/containers/Viewer/Viewer.tsx, src/containers/Viewer/ViewerComponent.tsx, src/containers/Viewer/ViewerDialog.tsx
Extracted Drag&Drop & file upload related logic to its own component, using both in reviewablesList and the viewer main pane when no reviewables exist.
https://github.com/user-attachments/assets/6abd5009-c540-4f57-bcef-2581673d559a
Closed #639
=> Viewer: Show dropzone when no reviewables

src/containers/SettingsEditor/SettingsEditor.sass, src/containers/SettingsEditor/fields.jsx
Use sane widths for elements in settings compact layout
=> Settings: improve compact layout in settings

src/pages/EditorPage/EditorPanel/EditorPanel.jsx, src/pages/EditorPage/EditorPanel/helper/callbacks.js, src/pages/EditorPage/EditorPanel/helper/entityHelpers.ts
Crash caused by complicated logic when identifying if values have changed in the editor page
https://github.com/user-attachments/assets/2d1ca9ba-f980-4046-8eab-f31cc5e27776
=> Editor: Fixed crash condition on assignee update

src/app.jsx, src/containers/DetailsPanel/DetailsPanel.jsx, src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.jsx, src/containers/DetailsPanel/DetailsPanelSlideOut/DetailsPanelSlideOut.jsx, src/containers/Viewer/ViewerDetailsPanel.jsx, src/hooks/useScopedStatuses.ts, src/pages/BrowserPage/BrowserDetailsPanel.jsx, src/pages/BrowserPage/Products/Products.jsx, src/pages/EditorPage/EditorPage.jsx, src/pages/EditorPage/EditorPanel/EditorPanel.jsx, src/pages/InboxPage/InboxDetailsPanel.jsx, src/pages/TasksProgressPage/TaskProgressDetailsPanel.jsx, src/pages/TasksProgressPage/TasksProgressPage.tsx, src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardKanBan.jsx, src/pages/UserDashboardPage/UserDashboardTasks/UserTasksContainer.jsx, src/services/userDashboard/getUserDashboard.ts
Entity status selector now reflects the project anatomy configuration. States that are not available for the entity are hidden
https://github.com/user-attachments/assets/905345d7-bf85-4b17-a461-3c278a3ee70a
Closes #823
=> Statuses: Statuses filtered by project scope configuration

src/pages/ProjectAddon.jsx, src/pages/SettingsPage/SettingsAddon.jsx
=> Addons: Removed overlay blocking addon iframe

src/services/installers/getInstallers.ts, src/services/project/getProject.ts
Not fully clear on where the error happens as I couldn't reproduce it...
Closes #861
=> Bundles: Avoiding potential errors caused by server restart

playwright.config.js, src/pages/SettingsPage/UsersSettings/DeleteUserDialog.tsx, tests/auth.setup.js, tests/fixtures/authenticationPage.ts, tests/fixtures/browserPage.ts, tests/fixtures/installRelease.ts, tests/fixtures/taskPage.ts, tests/fixtures/userPage.ts
A few fixes to the specs, attempting to make them pass on each repeat.
Closes #818
=> Specs: Fixing faulty specs

src/containers/TasksProgress/components/FolderBody/FolderBody.styled.ts, src/containers/TasksProgress/components/FolderBody/FolderBody.tsx, src/containers/TasksProgress/components/ParentBody/ParentBody.tsx, src/containers/TasksProgress/components/TasksProgressTable/TaskProgressTable.scss, src/containers/TasksProgress/components/TasksProgressTable/TasksProgressTable.tsx, src/styles/index.scss
- Increase the size of the folder thumbnail when the row is increased
- Adds row separation lines
- Removes folder parent prefix
- Parents headers are sticky
=> Task Progress: Table style improvements

src/containers/SettingsEditor/FormTemplates/ArrayFieldTemplate.tsx, src/containers/SettingsEditor/SettingsEditor.jsx, src/containers/SettingsEditor/SettingsEditor.styled.tsx, src/containers/SettingsEditor/Widgets/SelectWidget.tsx, src/containers/SettingsEditor/Widgets/TextWidget.tsx
These changes remove most - if not all - console warnings in the settings page. 
They seem safe, please have a look though, I might have removed some that are needed
=> Maintenance: Code & console warnings cleanup

src/pages/EventsPage/EventList.jsx
=> Events: Removed row icon ellipsis in events table

src/pages/SettingsPage/AddonInstall/AddonUpload.jsx
https://github.com/user-attachments/assets/a78d3974-3da6-4057-abbe-c4f7276f35ee
=> Addons: Fixed Cancel/Close button message on addon upload

src/containers/RawSettingsDialog/RawSettingsDialog.jsx
https://github.com/user-attachments/assets/1a9c7ef5-4f98-4b2e-bfbe-0bbb38d2b586
Closes #888
=> Settings: Fixed scroll behavior in raw edit mode

src/containers/SettingsEditor/FormTemplates/ArrayFieldTemplate.tsx, src/containers/SettingsEditor/SettingsPanel.jsx
Fixed scroll behavior for large array field templates
https://github.com/user-attachments/assets/53206976-2c6b-40a5-87c6-ee3e38e1a0b3
=> Settings: Wide settings lists are now scrollable

src/containers/SettingsEditor/FormTemplates/ArrayFieldTemplate.tsx
https://github.com/user-attachments/assets/e22c6b91-5265-468f-8bd6-c281bddf9be7
Closes #894
=> fix(Settings): Min container width set to 100% to avoid narrow content issues

src/components/Thumbnail/Thumbnail.tsx, src/hooks/useFocused.js, src/pages/EditorPage/EditorPanel/EntityTumbnailUploaderRow.tsx, src/services/userDashboard/userDashboardHelpers.js
Issue was caused by wrong entity type passed around on while gathering detail data.
https://github.com/user-attachments/assets/c1dfaf03-bfa8-4f08-99d1-f5e1a5eaaaa6
=> fix(Editor): Fixing thumbnails upload in editor page

src/pages/SettingsPage/Bundles/Bundles.jsx, src/pages/SettingsPage/Bundles/CopyBundleSettingsDialog/CopyBundleSettingsDialog.tsx
Copy settings from bundle... right click was not working as no target environment (prod, staging, dev) was provided.
- Fixed issue.
- Improved error message to show to user of something goes wrong.
=> Bundles:  copy settings from... broken

package.json, src/api/graphql.ts, src/components/SearchFilter/SearchFilter.styled.ts, src/components/Thumbnail/Thumbnail.tsx, src/containers/TasksProgress/TasksProgress.tsx, src/containers/TasksProgress/components/FolderBody/FolderBody.styled.ts, src/containers/TasksProgress/components/FolderBody/FolderBody.tsx, src/containers/TasksProgress/components/ParentBody/ParentBody.styled.ts, src/containers/TasksProgress/components/ParentBody/ParentBody.tsx, src/containers/TasksProgress/components/TasksProgressTable/TasksProgressTable.tsx, src/containers/TasksProgress/helpers/formatTaskProgressForTable.ts, src/containers/TasksProgress/helpers/taskStatusSortFunction.ts, src/features/progress.ts, src/features/store.ts, src/pages/TasksProgressPage/TaskProgressDetailsPanel.tsx, src/pages/TasksProgressPage/TasksProgressPage.tsx, src/services/tasksProgress/gql/ProgressTaskFragment.graphql
- Select a parent folder to open it in the details panel.
- Expanded rows now uses the EntityCard design for the folder.
- Fixed a sorting bug that caused a crash.
- Fixed thumbnails and icons not showing for parent folder.
https://github.com/user-attachments/assets/c1ad0c2e-afeb-4536-b9f0-ed4548face98
=> Task Progress: Folder selection

src/containers/SettingsEditor/SettingsEditor.jsx, src/pages/EditorPage/EditorPanel/EditorPanel.jsx, src/pages/EditorPage/EditorPanel/helper/entityHelpers.ts
https://github.com/user-attachments/assets/94bae78d-a48e-4c12-8593-251c1d2999d0
=> Editor: Displaying correctly numeric 0/empty values

src/containers/AddonSettings/AddonSettings.jsx, src/containers/SettingsEditor/Widgets/CheckboxWidget.tsx, src/containers/SettingsEditor/Widgets/SelectWidget.tsx, src/containers/SettingsEditor/Widgets/TextWidget.tsx
https://github.com/user-attachments/assets/d35978e7-2551-4a81-9374-92d5ea997fef
=> fix(Settings): Default values set for fields that that are specifically null/undefined

src/components/EmptyPlaceholder/EmptyPlaceholderFlex.styled.ts, src/pages/ProjectManagerPage/ProjectManagerPage.jsx, src/pages/ProjectManagerPage/ProjectPermissions.jsx, src/pages/ProjectManagerPage/Users/ProjectUserAccess.styled.ts, src/pages/ProjectManagerPage/Users/ProjectUserAccess.tsx, src/pages/ProjectManagerPage/mappers.ts, src/pages/SettingsPage/AccessGroups/index.tsx
Typo in mapper caused permissions tab to never match module name
=> Permissions: UI/UX fixes & typo bugfix

src/containers/Breadcrumbs/Breadcrumbs.jsx, src/containers/SettingsEditor/SettingsEditor.jsx, src/context/uriContext.jsx
Reverted conditional introduced to avoid navigation to browser page while in the dashboard page and refreshing page, added specific check to deal with dashboard -> browser navigation.
https://github.com/user-attachments/assets/a5dbcbf6-9b48-4a71-9558-eb6318db0d68
Closes #952
=> fix(URI): Removed wrong conditional that blocked navigation on URI init

src/app.jsx, src/components/Customerly.tsx, src/components/TrialBanner/TrialBanner.tsx, src/containers/TrialEnded/TrialEnded.tsx, src/hooks/useCustomerly.ts
Now when the playground addon is present the customerly bubble will appear.
Puts customerly on a global level so it's easier to enable for any other reason.
=> Customerly: rewrite customerly to work with playground

src/pages/SettingsPage/UsersSettings/UserList.jsx
Add default projects access column to user settings table.
=> Users: Default projects access column

LICENSE
License change reflecting the announcement here https://ynput.io/blog/ayon-server-is-adopting-fair-source/
=> License change from Apache 2.0 to FSL-1.1-ALv2

src/components/EntityPath/EntityPath.tsx, src/components/EntityPath/SegmentProvider.tsx, src/containers/DetailsPanel/DetailsPanel.jsx, src/containers/DetailsPanel/DetailsPanel.styled.js, src/containers/Viewer/Viewer.styled.ts, src/context/uriContext.jsx
- The reviewables list would be over the slideout panel in the viewer.
- Condensed down the slideout panel path segments to better fit in the tools.
=> Fix: Slide bug fixes

src/context/shortcutsContext.jsx
1. Go to project settings page with double p shortcut.
2. Double tap a shortcut.
3. It should navigate to anatomy.
=> Internal: Odd shortcut behaviors

src/pages/MarketPage/MarketFilters.tsx, src/pages/MarketPage/MarketPage.jsx
=> Market: Show all addons by default

src/containers/Viewer/Viewer.tsx
- remove the `useEffect` hook which effectively disables the "autoplay on spacebar" feature of the Viewer
=> Re-enable video autoplay when opening the Viewer using the spacebar

src/pages/EditorPage/EditorPage.jsx
Frontend counterpart to https://github.com/ynput/ayon-backend/pull/530
Handles different 409 responses from operations differently
=> Editor: use errorCode from operation response

src/remote/remoteModulesContext.tsx, vite.config.ts
Remove ARC package from shared libraries as it was causing caching issues when upgrading containers (maybe).
=> MF: Remove arc module sharing

src/pages/ServicesPage/NewServiceDialog.jsx
Service names should follow these AWS bucket names. Services are not always used with AWS but this is fairly good naming validation anyway.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html#general-purpose-bucket-names
=> Services: Abide by AWS bucket naming rules

gen/openapi-config.ts, src/api/rest/auth.ts, src/api/rest/cloud.ts, src/app.jsx, src/components/CompleteProfilePrompt/CompleteProfilePrompt.tsx, src/components/Menu/MenuComponents/Menu.jsx, src/components/Menu/MenuComponents/MenuItem.jsx, src/components/Menu/Menus/AppMenu.jsx, src/components/Menu/Menus/HelpMenu.jsx, src/feedback/FeedbackContext.tsx, src/pages/AccountPage/AccountPage.jsx, src/services/auth/getAuth.js, src/services/ayon.ts, src/services/cloud/cloud.ts, src/services/user/getUsers.ts, src/services/user/updateUser.ts
- Auto authentication with hashing of AYON users so that they do not need to create featurebase account themselves.
- Should appear everytime a new changelog item is added OR when the "Latest changes" button in the help menu is selected.
- Production addons are included in the categories to be shown. ("Planner Addon")
- Admins see all "Server" and "Production Tracking" category changes.
- Regular users only see "Production Tracking" changes.
- "Submit feedback" in the help menu.
- "Help center" in the help menu.
- A button in the bottom left/right corner is possible but currently it gets in the way.
- The devs have said that this whole thing will be improved very soon.
- "Upcoming features" in the help menu opens the help center on the roadmap page.
New help menu items.
Because an email …
=> Changelogs, road maps, help and feedback

gen/openapi-config.ts, src/api/rest/config.ts, src/pages/ProjectManagerPage/NewProjectDialog/AnatomyPresetDropdown.jsx, src/pages/ProjectManagerPage/NewProjectDialog/NewProject.jsx, src/services/config/getConfig.ts
This pull request introduces new functionality to retrieve configuration values from the server and refactors some existing code to accommodate this new feature. Additionally, it includes minor improvements and cleanups in the codebase.
* Added a new endpoint `getConfigValue` to retrieve specific configuration values from the server.
* Refactored the `createCode` function in `NewProjectDialog` to use the user-defined regex from the server configuration instead of hardcoded logic.
* Default regex is `^.{0,3}`
1.  **Simple Acronym (First Letters):**
```regex
\b(\w)
```
**Purpose:** Extracts the first letter of each word.
**Example:** `Crimson_Tide_of_Atlantis` -> `CTOA`
2.  **Specific Word Extraction:**
```regex
(Solar|Lunar)
```
**Purpose:** Extracts specific keywords like "Solar" or …
=> Projects: Use a regex to generate project code

shared/src/ProjectTreeTable/context/ClipboardContext.tsx
Lets the user know specifically why copy/pasting is not working.
=> Overview: Better error messages for clipboard errors

shared/src/ProjectTreeTable/context/CellEditingContext.tsx, shared/src/ProjectTreeTable/widgets/CellWidget.tsx
Validates values based on requirements set in attributes definition.
=> Overview: Validate field values based on attribute

src/containers/Actions/ActionConfigDialog.tsx, src/containers/Actions/Actions.jsx, src/containers/Actions/InteractiveActionDialog.tsx, src/containers/SimpleFormDialog/SimpleFormDialog.tsx, src/hooks/useActionTriggers.ts
This pull request refactors the handling of user interactions and action payloads, improves the configuration dialog for actions, and introduces a more consistent API for managing form dialogs. 
* Replaced the `header` property with `title` in `SimpleFormDialog`, `ActionConfigDialog`, and `InteractiveActionDialog`, and added support for `submitLabel`, `cancelLabel`, `submitIcon`, and `cancelIcon` to allow more customization of dialog buttons. 
* Refactored `useActionTriggers` to use more descriptive action types (e.g., `launcher`, `query`, `navigate`, `redirect`) 
* Moved the `customProtocolCheck` logic from `Actions.jsx` to `useActionTriggers` for better separation of concerns.
This is a frontend counterpart of https://github.com/ynput/ayon-backend/tree/584-webactions-general-webactions-e …
=> Sync with new action response model

package.json, src/components/ActionsDropdown/ActionsDropdown.jsx, src/remote/Loaders/AppRemoteLoader.tsx, yarn.lock
Providers remote apps with `location` `searchParams` `setSearchParams` and `history`.
=> Remote: Provide remote apps with location

shared/package.json, shared/src/context/DetailsPanelContext.tsx, shared/src/hooks/useEntityUpdate.ts
Add a simple handler prop to `DetailsPanelProvider` which allows the host app to be notified if the user changes the entity using the details panel.
The callback will be passed the operations array and entity type.
=> Expose an `onUpdateEntity` callback from `DetailsPanelProvider`

shared/src/containers/RepresentationsList/RepresentationsList.tsx
Fixed missing representation list caused by an incorrect conditional render.
=> Missing representation list

src/feedback/FeedbackContext.tsx, src/pages/LoginPage/LoginPage.jsx, src/pages/LoginPage/LoginPage.styled.jsx
Add terms of service and privacy policy to login page to ensure we are completely transparent about the data we collect.
=> Privacy policy note

shared/src/api/generated/system.ts, src/feedback/FeedbackContext.tsx
This pull request updates the `FeedbackProvider` component in `src/feedback/FeedbackContext.tsx` to incorporate site-specific configurations retrieved from the API. The changes ensure that feedback-related features and categories are dynamically adjusted based on the site's settings.
Requires https://github.com/ynput/ayon-backend/pull/614
=> Optionally disable changelog pop-ups for users

src/app.tsx
Fixes an issue that would causes remote modules not to load properly for regular users. This most noticeable with the viewer annotations being disabled.
=> Modules: Not loading correctly for users

shared/src/containers/ProjectTreeTable/hooks/useCellContextMenu.ts, shared/src/containers/ProjectTreeTable/hooks/useDeleteEntities.ts, src/pages/ProjectOverviewPage/components/OverviewActions.tsx
Deleting entities from selection would include all selected cells and row selections. This would create duplicates and be confusing.
=> Overview: Fix deleting entities selection issues

shared/src/api/queries/entities/transformDetailsPanelData.ts, shared/src/components/DetailsPanelAttributes/DetailsPanelAttributes.tsx
=> Details Panel: Correctly format path for each entity type

src/components/NewEntity/NewEntity.tsx
=> Overview: Add selected parent label to new entity dialog

src/containers/CopySettings/CopySettingsNode.jsx
This pull request includes a minor update to a comment in the `CopySettingsNode` component. The change is purely cosmetic and does not affect functionality.
* Updated the age mentioned in a comment from 40 to 41 in `CopySettingsNode` for accuracy.
=> Updated temporal offset in comment

shared/src/api/generated/graphql.ts, shared/src/api/queries/folders/getFolders.ts, shared/src/api/queries/overview/getOverview.ts, shared/src/api/queries/overview/gql/GetTasksList.graphql, shared/src/containers/ProjectTreeTable/ProjectTreeTable.tsx
The overview table now has real time updates so that you can see changes to entities without needing to refresh.
This improves collaboration between teams so that everyone is in sync on the status of the project.
Links are currently not supported. Coming soon.
=> Overview: Real time updates

src/pages/UserDashboardPage/UserDashboardTasks/KanBanColumn/KanBanColumn.jsx
=> Home: Task Open in browser fix

src/containers/SettingsEditor/SettingsEditor.sass, src/containers/SettingsEditor/Widgets/SelectWidget.tsx
This pull request enhances the `SelectWidget` component in the settings editor by introducing a new "switchbox" widget type for multi-select options. It also includes a small styling improvement for form field labels.
=> Switchbox component for the settings editor

src/components/NewEntity/NewEntity.tsx, src/components/NewEntity/NewEntityForm.tsx, src/context/NewEntityContext.tsx
Enhanced NewEntity component with smart auto-generation of entity names and improved form reusability across single entity creation and sequence creation workflows.
Key Features:
- Smart name auto-generation: Names are automatically generated from labels, but stop auto-updating once the user manually edits the name field
- Unified form component: Created reusable NewEntityForm component that works in both single entity creation and folder sequence creation
- Label/Name separation: Clear distinction between display labels and backend names with proper sanitization
- Editable name field: Users can click on the generated name to edit it manually
- Consistent lowercase naming: All generated names are lowercase with proper character sanitization
- NewEntity.tsx: Added nameManuallyEdited state …
=> Overview: Creating new entity should set label with autogen name #1356

shared/src/components/LinksManager/LinkManagerItem.tsx, shared/src/components/LinksManager/LinksManager.styled.ts, shared/src/components/LinksManager/LinksManager.tsx
Add close icon to LinksManager dialog, change the close icon to delete(Trash bin) icon in links list
=> Overview: closing multilink dialog with button

shared/src/containers/ProjectTreeTable/hooks/useCellContextMenu.ts, src/components/ErrorFallback.jsx, src/components/NewEntity/NewEntity.tsx, src/containers/VideoPlayer/VideoPlayerControls.jsx, src/pages/InboxPage/Inbox/Inbox.jsx, src/pages/ProjectManagerPage/Users/ProjectUserAccessAssignDialog.tsx, src/pages/SettingsPage/Bundles/BundleDetail.jsx, src/pages/SettingsPage/Bundles/BundleList.jsx, src/pages/SettingsPage/Bundles/NewBundle.jsx, src/pages/SettingsPage/UsersSettings/newServiceUser.jsx, src/pages/SettingsPage/UsersSettings/newUser.jsx, src/pages/UserDashboardPage/hooks/useGetTaskContextMenu.js
…getPlatformShortcutKey` utility for platform-specific consistency.
Refactored shortcut handling: replaced hardcoded shortcut strings with `getPlatformShortcutKey` to ensure consistent display of CMD/CTRL/Shift shortcuts across platforms.
=> Cleanup shortcut labels

shared/src/containers/ProjectTreeTable/ProjectTreeTable.tsx, shared/src/containers/ProjectTreeTable/buildTreeTableColumns.tsx
- Ensure all columns have correct sorting model for client side (when hierarchy on).
- Ensure client side sorting is turned off so that server sorting working
=> Table: Ensure sorting works correctly for client and server.

src/pages/SettingsPage/Bundles/BundlesAddonList.tsx
Fixed a bug where selecting multiple addons in the bundle editor would cause version dropdowns for non-selected addons to become blank
- The fix ensures that non-selected addon rows always display their own available versions, even when multiple other addons are selected
- Handles the inconsistency where PrimeReact DataTable can pass selection as either an array (normal multi-select) or a single object (context menu clicks)
- No breaking changes to the component API
=> Bundles: Addon multi selection causing hidden versions
