src/styles/index.sass

`position: fixed;` on `body` parent of `Toast` was causing some weird z-index issues as the `Dialog` was outside of `body`. Changing to `position: absolute` fixed z-index behaviour.

Fix toast z-index to be higher than dialog

---

src/containers/hierarchy.jsx
src/containers/tagsEditor/createButton.jsx
src/containers/tagsEditor/dialog.jsx
src/containers/tagsEditor/editor.jsx
src/containers/taskList.jsx

Create new tags without leaving the tags editor dialog. These tags aren't set globally and are set locally for that entity.
- Could do with a better way of distinguishing between "gobal" and "artist" (local) tags.
- Maybe this would be better as an Addon?
- Artist tags currently have no color assigned to them.

Enhancement: Add "artist" new tags

---

src/containers/hierarchy.jsx
src/containers/tagsEditor/createButton.jsx
src/containers/tagsEditor/dialog.jsx
src/containers/tagsEditor/editor.jsx
src/containers/tagsEditor/index.jsx
src/containers/taskList.jsx
src/pages/browser/subsets.jsx

Allow the user to edit the tags of multiple entities at once.
- Currently all tags overwrite the previous tags for all entities selected.
- Warnings have been added so the user understands the risks of overwriting tags
- Future/Addon could allow the user to choose this overwriting behaviour (would require more advanced UI and a logic rewrite).
- Bugs: List of version names shows version names (v004, v004, v002) which isn't helpful.

Enhancement: multi entity tag support

---

src/containers/tagsEditor/editor.jsx

Fixes a bug where the width of the dialog could change size when searching for tags. Now the width stays fixed.
- Width stays fixed when searching
- Available becomes scrollable when the height is overflown.
- When no tags are assigned the height doesn't change.
- Show a message when no search results match
- Search for tags so that none match, the width should stay the same width.
- Create lots of new tags so that the height overflows and Available becomes scrollable.

Fix: width and height changing

---

src/components/OptionsDropdown.module.scss
src/components/dropdown.jsx
src/components/status/statusField.jsx
src/components/status/statusSelect.jsx
src/containers/attributeTable.jsx
src/containers/fieldFormat.jsx
src/pages/browser/folderDetail.jsx
src/pages/browser/subsets.jsx
src/pages/browser/subsetsUtils.jsx
src/pages/browser/taskDetail.jsx
src/pages/browser/versionDetail.jsx
src/pages/project.jsx
src/styles/index.sass
src/utils.js

Select and change an entity status by clicking on it and selecting from a dropdown.
- `StatusSelect` and `StatusField` components reusable across the app.
- New `OptionsDropdown` dropdown that's agnostic and reusable.
- `onChange` handlers post data and then reload data automatically.
- `StatusField` has `alignment` and `size` props.
- Uses pure CSS for all styling effects to optimise speed.
- Status reflects changes instantly (before db request has resolved).
- Status has a nice highlighted to fading off effect to emphasise a change.
- `StatusSelect` `size` changes based on status column size.
- Width is calculated using length of longest status.
- Icons default to circle when not found (API needs updating).
- If two of the same status are shown in different areas of the app, the none …

Feature: Status Select Dropdown MVP

---

src/components/dropdown.jsx
src/components/status/statusSelect.jsx
src/pages/browser/subsets.jsx

When a user selects multiple subsets and then goes to change a status outside of that subset it would only change the selection. 
- Now selecting a status outside a selection removes the selection and changes only the one status.
- Other behaviours could be that the "outside" subset is added to the selection.
1. Select multiple subsets.
2. Click on a status of a subset outside the selection.
3. The status dropdown should not show "x selected".
4. The selection should jump to only the new status clicked on.

fix select status outside of selection bug

---

src/components/dropdown.jsx
src/components/status/statusSelect.jsx
src/pages/browser/subsets.jsx
src/pages/editor/index.jsx

Resize, reorder and filter columns in subsets and editor.
- Resizing columns saves to `localStorage` for persistence.
- Reordering columns saves to `localStorage` for persistence.
- Filtering columns saves to `localStorage` for persistence.
- Subsets has two separate column filters, single and multiple selected folders. 
There's currently a lot of repeated code between `src/pages/browser/subsets.jsx` and `src/pages/editor/index.jsx`. I tried to share as much as possible but both are set up differently so it was tricky. If another pages uses these features it might be worth creating a wrapper/HOC. 
1. Go to `/projects/demo_Commercial/browser`.
2. Check/uncheck columns in the dropdown.
3. Now select multiple folders in the hierarchy (on the left)
4. The previous filters should reset (or …

Feature: Subsets and Editor column reordering, resizing and filtering

---

src/containers/hierarchy.jsx
src/features/context.js

Fixes a bug where the wrong `focusedType` was set when opening the folder tags editor.
This would happen because right clicking of a folder doesn't change the `focusedType` to `folder`. This is now fixed.
1. Click on a folder
2. Click on a subset/version/task
3. Right click on the same folder and click 'Edit Tags'
4. The tags editor should be editing the folders tags (before it would be stuck to the selection on step 2).

fix wrong focusedType of tags editor

---

src/app.jsx
src/components/status/statusSelect.jsx
src/containers/header/breadcrumbs.jsx
src/containers/header/projectMenu.jsx
src/containers/hierarchy.jsx
src/containers/tagsEditor/index.jsx
src/features/context.js
src/pages/browser/BrowserPage.jsx
src/pages/browser/RepresentationList.jsx
src/pages/browser/Subsets.jsx
src/pages/browser/detail/Detail.jsx
src/pages/browser/detail/FolderDetail.jsx
src/pages/browser/detail/TaskDetail.jsx
src/pages/browser/detail/VersionDetail.jsx
src/pages/editor/index.jsx
src/pages/workfiles/index.jsx

Fix an issue with `useSelector((state) => ({... state}))` would cause re-renders whenever the state changed.
The spreading of the state into an object meant `useSelector` always returned a new object reference, and so the component would re-render after every action even if the state data didn't change. 
[Redux Essentials, Part 6: Performance and Normalizing Data](https://redux.js.org/tutorials/essentials/part-6-performance-normalization#investigating-render-behavior)
[Deriving Data with Selectors](https://redux.js.org/usage/deriving-data-selectors#optimizing-selectors-with-memoization)
A better way is to be more selective with the selector and use `useSelector` multiple times.
```javascript
const projectName = useSelector((state) => state.context.projectName)
const focusedTasks = …
```

Fix: use selector rerender fixes

---

src/containers/thumbnail.jsx
src/styles/index.sass

The thumbnail was overflowing its parent container.
- Parent will always be `aspect-ratio: 16/9;`.
- Img child uses `object-fit: contain;` so that it never overflows no matter it's size or aspect ratio.
- Added `border-radius: 3px;` .
- Improved placeholder styling.
- Moved styles to use `styled-components` inseatd of `sass` file.

fix: thumbnail overflowing

---

src/hooks/useSearchFilter.js
src/pages/settings/users/UserImagesStacked.jsx
src/pages/settings/users/UserList.jsx
src/pages/settings/users/UserTile.jsx
src/pages/settings/users/UsersOverview.jsx
src/pages/settings/users/UsersSettings.jsx
src/pages/settings/users/userDetail.jsx
src/services/user/getUsers.js

When no user is a selected a panel with helpful stats and shortcut buttons.
- Show total users, admins, services, managers.
- Clicking between projects changes these values based on the number of users in assigned to the project.
- Clicking on **Total** selects all users shown in list.
- Clicking **Admin, Service, Manager** prefills the search bar with the user type to filter through the list and only show that type.
- Search filter can now do inverse searches and remove results that match the search with adding `!` to the beginning. For example `!admin` will show everything but matches for "admin". 
- Clicking **Users** does the opposite by filling the search bar with `!admin, !service, !manager`. This shows all users that aren't one of those.
- Show last updated user on the project with …

Enhancement: User Page Overview

---

src/components/ApiKeyManager.jsx
src/components/LockedInput.jsx
src/hooks/useSearchFilter.js
src/pages/settings/users/ServiceDetails.jsx
src/pages/settings/users/SetPasswordDialog.jsx
src/pages/settings/users/UserAccessForm.jsx
src/pages/settings/users/UserList.jsx
src/pages/settings/users/UsersSettings.jsx
src/pages/settings/users/newUserDialog.jsx
src/pages/settings/users/userDetail.jsx
src/services/user/getUsers.js
src/services/user/updateUser.js

- Create and delete API Keys for `service` users.
- One time copy of new key.
- Blurred preview of key.
- Removed a lot of irrelevant fields for `service` users.
- The user header now displays all the roles for those users.
1. Create a new user with the `userLevel: service`.
2. Click on new user and click the plus button in the API Key field.
3. A new key should appear with a copy icon.
4. Click off and then onto the user, the key should now be gone and only the preview can be seen.
5. Click on the trash icon to delete the key.

Feature: Service Api Keys

---

src/containers/hierarchy.jsx
src/pages/projectManager/index.jsx

- Double click a folder in Hierarchy to expand/close it.
- Selecting multiple folders and then double clicking (whilst still holding down `shift`) expands all selected.
- Not implemented on editor as double clicking currently puts your into edit mode.
- Fix: projectManager toolbar links were wrongly hidden for admins and managers.

Cosmetic: double click expand tree

---

src/components/ShareDialog.jsx
src/pages/projectDashboard/panels/GridLayout.jsx
src/pages/projectDashboard/panels/ProgressBar.jsx
src/pages/projectDashboard/panels/ProgressTile.jsx

If the panel was overflowing and showing scrollbars then the created share image would also show them. This is now fixed so that the whole panel is captured.
Other improvements to the share dialog UI.

fix: share image overflow fixed

---

src/pages/projectAddon.jsx

Access to project name was lost in Addon when context was split out into project and context.
Found by @Minkiu

fix: merge project name into context

---

src/containers/attributes/attributeEditor.jsx
src/pages/editor/index.jsx
src/pages/settings/Attributes.jsx
src/pages/settings/users/UsersSettings.jsx
src/pages/settings/users/userDetail.jsx

Adds a boolean setting on attributes which turns on/off its inheritance. When set to on (default), children entities inherit the value from the parent unless the value is explicitly set. This is useful for metadata such as 'description' which only make sense on a single entity.

Op 5215/toggleable attribute inheritance

---

src/pages/editor/index.jsx

Expanding a folder in the browser (hierarchy) will now also expand and load same folder in the editor automatically.

fix: concat expanded folders on initial query

---

src/pages/SettingsPage/UsersSettings/UserList.jsx

Move profile image to the same column as username to fix profile column being too big on ayon.dev

Fix: Users Table Profile Column

---

src/helpers/checkName.js
src/pages/EditorPage/EditorPage.jsx

- Checks the regex `/^[a-zA-Z0-9_][a-zA-Z0-9_.-]*[a-zA-Z0-9_]$/`
- If regex fails it converts the string to camel_case

fix: entity name check regex + uses snake_case on fail

---

src/containers/addonSettings/AddonSettings.jsx
src/pages/ProjectManagerPage/ProjectManagerPageContainer.jsx
src/pages/ProjectManagerPage/ProjectManagerPageLayout.jsx

`<ProjectManagerPageLayout />` was causing the layout to be wrong in settings. So now it is completely ignored outside of Project Manager page context.

fix: Project/Studio settings toolbar broken

---

src/hooks/useSearchFilter.js
src/pages/EventsPage/EventsPage.jsx
src/services/events/getEvents.js

- Now when searching, more data will be queried with the search string as a filter.
- Filtered queries will still only return 100 events, so more queries will be fetched on the user reaches the bottom.
- Fixed a bug where events that already existed would be pushed onto the events again instead of being updated.

Enhancement: events server side filtering

---

src/containers/header/projectMenu.jsx

When switching projects, if you are on the editor page, then you should stay on the editor page once switched.

fix: switching projects should persist current page

---

src/pages/EditorPage/NewEntity.jsx

When creating a new folder/task in editor, preselect the default text, usually "folder" or "generic", so that you can quickly rename it.

Preselect name input

---

src/pages/BrowserPage/RepresentationList.jsx
src/pages/EditorPage/EditorPage.jsx

- Having two "add folders" button was unnecessary and confusing.
- Now you can create "root" folders by using the "add folder" button when nothing is selected.
- Or by right clicking in the table (but not on a specific table row).
- Ability to deselect rows.

Fix: Remove Root Folder

---

src/components/User/UserDetailsHeader.jsx
src/pages/BrowserPage/RepresentationList.jsx
src/pages/ProfilePage.jsx
src/pages/SettingsPage/UsersSettings/newUser.jsx
src/pages/SettingsPage/UsersSettings/userDetail.jsx
src/pages/TeamsPage/CreateNewTeam.jsx
src/pages/TeamsPage/TeamDetails.jsx
src/pages/TeamsPage/TeamUsersDetails.jsx

Switch so that "save" or "create" is always on the left
Also... small redesign of team settings panel.

Fix: user card buttons switch

---

src/containers/header/projectMenu.jsx
src/containers/header/userMenu.jsx
src/containers/projectList.jsx
src/pages/BrowserPage/RepresentationList.jsx
src/pages/ProfilePage.jsx

And also...
- Put Manage Projects at the top
- Add dividers to user menu
- Move sign out button to profile page
- Move restart server button to bottom

Op 6096 remove manage projects button from project lists menu

---

src/components/status/statusSelect.jsx

Fix an issue where selecting multiple statuses and then selecting the original (already selected) status wouldn't make any changes.

fix: multiple-select-status-fix

---

src/containers/TeamList.jsx
src/containers/addonSettings/AddonSettings.jsx
src/containers/header/projectMenu.jsx
src/containers/header/userMenu.jsx
src/containers/projectList.jsx
src/pages/ProjectDashboard/ProjectDashboard.jsx
src/pages/ProjectManagerPage/ProjectAnatomy.jsx
src/pages/ProjectManagerPage/ProjectManagerPage.jsx
src/pages/ProjectManagerPage/ProjectManagerPageContainer.jsx
src/pages/ProjectManagerPage/ProjectManagerPageLayout.jsx
src/pages/ProjectManagerPage/ProjectRoots.jsx
src/pages/TeamsPage/TeamsPage.jsx
src/pages/TeamsPage/UserListTeams.jsx
src/services/entity/getEntity.js

This is a bit of an experiment but I think it's an improvement.
- Open, Delete buttons have been completely removed.
- Other actions have been added to the context menu.
- This has also been done for the teams page.
- If these changes are made, we might need to rethink the button layout in settings as well.
Only problem might be tablet (touch screen) users not being able to reach "delete project". But then maybe deleting a project shouldn't be done on a touch screen device.

Redesign Manage Projects Buttons

---

src/components/ContextMenuItem.jsx
src/pages/TeamsPage/TeamUsersDetails.jsx
src/pages/TeamsPage/TeamsPage.jsx
src/pages/TeamsPage/UserListTeams.jsx
src/pages/TeamsPage/UserSubtitle.jsx
src/pages/TeamsPage/addRemoveMembers.js
src/styles/index.scss

These changes should make it far easier to understand what users are on what teams and how to add/remove them from a team.
- Fixed a bug where not all users would show when creating a new team
- Show all users by default
- Group users in the table by selected teams
- Add/Remove users to teams using context menu
- "quick add" button on Member Settings panel
- UX testing will be performed on the page to see these changes helped.

Teams UX Improvements

---

src/containers/hierarchy.jsx

This actually wasn't a bug and was the intended behaviour but I can see it would be very confusing to the user.
I have changed the behaviour to maintain the hierarchical structure (not flattened)

fix: filter by folder type maintains hierarchy

---

src/pages/TeamsPage/TeamsPage.jsx

Based on user research from @LiborBatek and @BigRoy, thank you!
Duplicating teams now shows a dialog for naming your newly duplicated team.

Fix: duplicating teams design fix

---

src/containers/taskList.jsx
src/pages/BrowserPage/Products.jsx
src/pages/BrowserPage/ProductsList.jsx
src/services/entity/getEntity.js
src/services/getProductList.js
src/styles/index.scss

Based on user research with @jakubjezek001, thanks! 🙏
- Selecting a task highlights matching products (by fading out non matching products)
- When a product is selected the normal view returns
- Ability to deselect tasks
- "Task" column in products table
- Removed two way pairing; selecting a product doesn't set the pairing, only selecting a task sets it now.

Fix: task selection highlights products

---

package.json
src/components/status/statusSelect.jsx
src/containers/entityDetail.jsx
src/pages/BrowserPage/Detail.jsx
src/pages/BrowserPage/Products.jsx
src/pages/BrowserPage/ProductsList.jsx
src/pages/EditorPage/EditorPanel.jsx
src/services/product/getProduct.js
src/styles/index.scss

- When selecting a new version, only the product version is loaded and not all the versions again.
- Increases speed of loading new versions.
- Improves the UX with single row loading.
- Removes hacky `versionOverrides` code.
- bumped components library version
- fixed a couple dropdown styles

enhancement: change product version loads only version

---

src/containers/hierarchy.jsx
src/pages/EditorPage/EditorPage.jsx
src/pages/EditorPage/EditorPanel.jsx

Thanks @LiborBatek 
- Fix bug that meant hierarchy parent folder couldn't be closed when child was selected.
- Select multiple folders and hold down `ctrl` (`cmd` for mac) to expand/close all selected folders.
- Removed double clicking to expand/close all in Hierarchy.

Fix: closing hierarchy parent when children selected + multiple close

---

src/styles/index.scss

- Sets default scroll width for firefox to be thin based on @BigRoy feedback.
- Set for the whole app, we will have to see if it's okay on windows, seems good on mac.
- Only affects firefox as it's the only browser that supports it.

fix: firefox scrollbar width to thin

---

package.json
src/components/ApiKeyManager.jsx
src/components/EntityGridTile.jsx
src/components/SearchDropdown.jsx
src/components/icons.jsx
src/components/status/statusField.jsx
src/containers/thumbnail.jsx
src/pages/EditorPage/EditorPage.jsx
src/pages/ProjectDashboard/panels/ListStatsTile.jsx
src/pages/ProjectDashboard/panels/ProgressTile.jsx
src/styles/index.scss

- All icons now use `<Icon icon="icon_name" />` component.
- The classname "icon" is always attached to the span to make styling easier. 
- Update components library that uses offline icons.

fix: replace all old icons with <Icon /> component

---

src/app.jsx
src/hooks/useServerRestart.js
src/pages/ProjectManagerPage/ProjectManagerPage.jsx
src/pages/SettingsPage/AddonInstall/AddonUpload.jsx
src/pages/SettingsPage/AnatomyPresets/AnatomyPresets.jsx
src/pages/SettingsPage/Attributes.jsx
src/pages/SettingsPage/Bundles/Bundles.jsx
src/pages/SettingsPage/UsersSettings/UsersSettings.jsx

- Created useServerRestart hook for easier use across the app.
- If a new addon has been installed on Bundles page, ask if server should restart.
- Move `<ConfirmDialog />` component to app.jsx file only.
```javascript
const { confirmRestart } = useServerRestart()
confirmRestart('Confirmation message here')
```

fix: addon prompt server restart

---

package.json
src/containers/AddonList.jsx
src/containers/AddonSettings/AddonSettings.jsx
src/context/websocketContext.jsx
src/pages/SettingsPage/Bundles/AddonList.jsx
src/pages/SettingsPage/Bundles/Bundles.jsx
src/pages/SettingsPage/Bundles/getLatestSemver.js
src/pages/SettingsPage/SettingsPage.jsx

- use semver package to get sort version dropdown and get latest version
- versioning up a bundle name was broken if there were more than 4 digits
- resetApiState on server restart connect
- Move Anatomy Presets nav item further down 
- bundles page search query fix
- improved settings bundle name can now be clicked to navigate to the bundle.
- addons list not updating when switching to an environment that had no bundle. `isError` is thrown but the addonsList data wasn't cleared, fixed now.

bundles fixes

---

src/containers/Breadcrumbs/Breadcrumbs.jsx
src/containers/Breadcrumbs/Breadcrumbs.styled.js
src/pages/ProjectPage.jsx

- Fix bug where project name wasn't getting set in uri
- Now show page name as a default
- Settings page shows "Studio Settings"
- Manage Projects page shows "Projects Manager"
- Make font size bigger and give secondary blue background to make breadcrumbs more prominent
- Fix auto selection bug not always selecting whole text
Thanks @m-u-r-p-h-y for the feedback

Fix: breadcrumbs show scope name

---

src/containers/AddonSettings/AddonSettings.jsx
src/containers/AddonSettings/CopySettings.jsx
src/containers/SettingsEditor/SettingsEditor.jsx
src/containers/SettingsEditor/SettingsPanel.jsx
src/containers/SettingsEditor/fields.jsx
src/containers/SettingsEditor/widgets.jsx
src/services/addonSettings.js

At the moment we are not able to save settings in case those are list with deep nested attributes. 
Here is the example of what will saving result into:
And here is the example of settings where the issue is occuring:
closes #185

Fix: propagating new complex items of arrays in settings

---

src/pages/OnBoarding/util/OnBoardingStep.styled.js
src/pages/OnBoarding/util/StepWrapper.jsx

- fix an issue where Styled.BG wasn't exported and would cause onboarding to crash if a background was present.

fix: onBoarding crashes with loginPageBG

---

src/components/ErrorFallback.jsx

- Remove broken auto reloading and just show button to reload when "TypeError: Failed to fetch dynamically imported module:"

Critical: error fallback for updates

---

src/context/shortcutsContext.jsx

I have done two things here:
1. Moved all shortcuts to be easily accessible by the left hand within the WASD area.
2. Removed more specific shortcuts like s+a and s+b as I believe they are too difficult to remember and inconsistent. Now all navigation shortcuts are always the same key twice.
Name | Old Key | New Key | Action
-- | -- | -- | --
**Unchanged**
Studio Settings | s+s | s+s | navigate to '/settings/studio'
Project Menu|1|1|Toggles the project menu open/closed
**Changed**
Users Settings | s+u | **f+f** | navigate to '/settings/users'
Dashboard | m+m | **d+d** | navigate to '/manageProjects/dashboard'
Project Settings | m+s | **a+a** | navigate to '/manageProjects/projectSettings'
Help Menu|8|**3**|Toggles the help menu open/closed
User Menu|9|**4**|Toggles the user menu …

enhancement: shortcuts moved to WASD

---

src/components/ApiKeyManager.jsx
src/containers/TeamList.jsx
src/containers/projectList.jsx
src/context/shortcutsContext.jsx
src/helpers/confirmDelete.js
src/pages/ProjectManagerPage/ProjectManagerPage.jsx
src/pages/ServicesPage/NewServiceDialog.jsx
src/pages/ServicesPage/ServicesPage.jsx
src/pages/SettingsPage/AccessGroups/AccessGroupDetail.jsx
src/pages/SettingsPage/AnatomyPresets/AnatomyPresets.jsx
src/pages/SettingsPage/AnatomyPresets/PresetList.jsx
src/pages/SettingsPage/Attributes.jsx
src/pages/SettingsPage/Bundles/Bundles.jsx
src/pages/SettingsPage/Secrets.jsx
src/pages/SettingsPage/UsersSettings/UserAttribForm.jsx
src/pages/SettingsPage/UsersSettings/UserList.jsx
src/pages/SettingsPage/UsersSettings/UsersSettings.jsx
src/pages/SettingsPage/UsersSettings/newUser.jsx
src/pages/TeamsPage/TeamsPage.jsx
src/styles/index.scss

- Anytime something is about to be deleted on the db, using confirmation popup.
- `confirmDelete` helper function that wraps `confirmDialog` with some defaults.
- Make sure all context menu delete items have `danger: true` prop for red bg.
Note: the hover effect on the delete button will be broken until a-r-c `0.4.8` is installed.

Fix: confirmation for delete buttons

---

package.json
src/containers/SettingsEditor/fields.jsx
src/pages/ProjectManagerPage/NewProjectDialog/NewProject.jsx

Project creation dialog: draw a red outline when project name or project code is wrong. Display actual error message as a tooltip.
Red outline is var(--color-hl-error) which should be used there, but it is not a very nice color. We should find a better one and include it to ayon-react-components.

OP-6657 show warning when name is wrong in create project dialog

---

package.json
src/components/FolderSequence/FolderSequence.jsx
src/pages/EditorPage/EditorPage.jsx
src/pages/EditorPage/EditorPanel.jsx
src/pages/EditorPage/NewEntity.jsx
src/pages/EditorPage/NewSequence.jsx
src/pages/EditorPage/TypeEditor.jsx
src/pages/SettingsPage/AnatomyPresets/AnatomyPresets.jsx

- New "Add folder sequence" tool for creating large amounts of sequential folders at one time.
- Improved UI of the original add folders and tasks tool to make creation quicker.
- New "Add" and "Add and Close" buttons to give the option to keep the dialog open after creating a folder/task.
- `folderType` anatomy now has new field `shortName`. For example "Sequence" has the default shortname "sq".
- New shortcuts:
- **Open ddd folder:** `n`
- **Open add folder sequence:** `m`
- **Open add task:** `t`
- New dialog shortcuts:
- **Add (but not close)**: `Shift+Enter`
- **Add and Close**: `Ctrl/Cmd+Enter`
1. Click "Add folders" button or hit "n" key or right click/Add folders
2. Select `Sequence` and `sq` should be set in the label input.
3. Change type again and the label should be updated …

Editor: Adding Multiple Folders and Tasks

---

src/containers/Breadcrumbs/Breadcrumbs.jsx
src/containers/hierarchy.jsx
src/containers/taskList.jsx
src/features/context.js
src/pages/BrowserPage/ProductsList.jsx
src/pages/WorkfilesPage/WorkfilesPage.jsx
src/styles/index.scss

- Persist task selection across folder selection changes. 
- For example if "fx" task is selected then selecting a different folder that also has the task "fx" will persist that original "fx" task selection.
1. In browser select a folder and then a task. Now select a new folder, the task selection **shouldn't** persist, should it?
2. In workfiles select a folder and then a task. Now select a new folder, the task **should** persist if the names match.
3. Select a folder and task and then copy the breadcrumbs. Now navigate to another page and paste breadcrumbs. Is the task selected on navigation?

Workfiles: persist task selection across folder selection changes

---

src/components/Menu/MenuComponents/Menu.jsx
src/components/Menu/MenuComponents/MenuContainer.jsx
src/components/Menu/MenuComponents/MenuItem.jsx
src/components/Menu/MenuComponents/MenuList.jsx

Link menu items use `<Link>` component that adds an `<a>` tag wrapper in the DOM for better accessibility, specifically middle/ctrl/cmd click to open in a new tab.

Menu: link menu items us "a" tag for better accessibility

---

src/app.jsx

-  Previously some pages would be exempt from bootstrapping redirect like '/events'. Now removed as it's confusing and not useful.
1. Launch bootstrapping from events page

Bootstrap: remove exception pages

---

src/components/FolderSequence/FolderSequence.jsx
src/pages/EditorPage/NewEntity.jsx
src/pages/EditorPage/NewSequence.jsx

- New dropdown ref interface needed to be used
- Fixes #215 
```
export interface DropdownRef {
getElement: () => HTMLDivElement | null
getOptions: () => HTMLUListElement | null
open: () => void
close: () => void
}
```

Editor: new entity dropdown ref fix

---

src/pages/ProjectDashboard/panels/ProjectDetails/ProjectDetails.jsx
src/pages/ProjectManagerPage/NewProjectDialog/NewProject.jsx
src/services/project/updateProject.js

- Add project Library attribute to project details panel, project details form and create new project.
- The library attribute in projects allows studios to load content like assets, images, 3D models, etc., across different projects.
1. Navigate to manage projects page.
2. Select project and on right hand side details panel click edit.
3. Turn library on/off.
4. Click save.
5. Library should have updated in the attributes panel.

Project: Set project library attribute

---

src/components/ProjectButton/ProjectButton.jsx
src/components/ProjectButton/ProjectButton.styled.js
src/containers/ProjectMenu/projectMenu.jsx
src/containers/ProjectMenu/projectMenu.styled.js
src/pages/ProjectDashboard/panels/ProjectDetails/ProjectDetails.jsx
src/pages/ProjectManagerPage/ProjectManagerPageContainer.jsx

- Add project code to projects menu and hide when hovering to reveal action buttons.
- Highlight current project in project menu.
- Add project code to projects table in project settings.
- Add project code to project details attribute table.

Projects Menu: Project code and highlighted

---

src/containers/AddonList.jsx
src/containers/AddonSettings/AddonSettings.jsx
src/containers/AddonSettings/AddonSettingsPanel.jsx
src/containers/SettingsEditor/SettingsEditor.jsx
src/containers/SettingsEditor/SettingsPanel.jsx
src/containers/SettingsEditor/fields.jsx
src/containers/SettingsEditor/widgets.jsx
src/hooks/useUriNavigate.js

URIs pointing to settings no longer require an addon version. Links point to versions currently enabled by default (the exact specification is still available using `addonName:addonVersion` format.

Settings: Addon version agnostic URIs

---

package.json
src/components/FolderSequence/FolderSequence.jsx
src/components/FolderSequence/FolderSequence.styled.js
src/components/status/statusSelect.jsx
src/pages/BrowserPage/Products.jsx
src/pages/BrowserPage/VersionList.jsx
src/pages/EditorPage/NewEntity.jsx
src/pages/EditorPage/NewSequence.jsx
src/pages/UserDashboardPage/UserDashboardNoProjects/UserDashboardNoProjects.jsx
src/pages/UserDashboardPage/UserDashboardPage.jsx

- Create new project button added to `dashboard/overview`
- New Folder/Task: focusing back to type selecting automatically opens it.
- New Sequence: If prefix switch isn't disabled focus now jumps top it.
- Bump ARC to `0.5.3` to fix switch.
- Version dropdown sort version descending @kalisp

Editor: New folder/task ergonomic improvements

---

src/components/Menu/MenuComponents/Menu.styled.js
src/components/Menu/MenuComponents/MenuItem.jsx
src/components/Menu/Menus/AppMenu.jsx
src/containers/header/AppNavLinks.jsx
src/context/shortcutsContext.jsx
src/pages/ProjectManagerPage/ProjectManagerPage.jsx
src/pages/SettingsPage/SettingsPage.jsx
src/pages/UserDashboardPage/UserDashboardPage.jsx

- New Shortcut: Project Anatomy `A+A`.
- New Shortcut: Settings Bundles `B+B`.
- Navigation tabs now short shortcut tooltip.
- App menu shows shortcut for item.

Shortcuts: New anatomy and bundles

---

src/containers/entityDetail.jsx

Revert the original behavior of entity detail dialog to use useGetEntityQuery instead of GraphQL.
Reason: This is the only place in the frontend, where a user can see the actual payload as available in REST, which is useful for debugging. It contains a complete entity payload as stored in the database along with its dynamic attributes.
Drawback: Only one entity is loaded at time, but i don't believe that is a major problem

Use REST endpoint instead of GraphQL to load entity detail

---

src/containers/AddonSettings/VariantSelector.jsx
src/pages/ServicesPage/NewServiceDialog.jsx

Services can now be configured to use a specific settings variant.
Variant selector is now included to "new service" dialog and sets AYON_DEFAULT_SETTINGS_VARIANT environment variable of the container. This is purely UX feature as the logic is already implemented in the API as well as in Ash

Pass settings variant to services

---

src/components/Details/EntityDetailsHeader.jsx
src/components/Details/EntityDetailsPanel.jsx
src/components/Details/ThumbnailGallery.jsx
src/components/EntityGridTile.jsx
src/components/ThumbnailUploader/ThumbnailUploader.jsx
src/components/ThumbnailUploader/ThumbnailUploader.styled.js
src/containers/thumbnail.jsx
src/pages/BrowserPage/Detail.jsx
src/pages/BrowserPage/ProductsGrid.jsx
src/pages/EditorPage/EditorPage.jsx
src/pages/EditorPage/EditorPanel.jsx
src/pages/EditorPage/StackedThumbnails.jsx
src/pages/UserDashboardPage/UserDashboardTasks/TaskAttributes/TaskAttributes.jsx
src/pages/UserDashboardPage/UserDashboardTasks/UserDashDetailsHeader/UserDashDetailsHeader.jsx
src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardDetails/UserDashboardDetails.jsx
src/pages/UserDashboardPage/UserDashboardTasks/UserTasksContainer.jsx
src/services/entity/entityQueries.js
src/services/entity/updateEntity.js
src/services/product/getProduct.js
src/services/userDashboard/updateUserDashboard.js
src/services/userDashboard/userDashboardHelpers.js
src/services/userDashboard/userDashboardQueries.js

- Click to upload or drag and drop, to add thumbnails to folders, tasks and versions.
- Upload multiple images: if multiple entities are selected and multiple files dropped, matching file to entity names will be uploaded. For example `sh010.png -> sh010, shot020.png -> sh020`.

Thumbnails: upload thumbnails from Browser, Editor and Dashboard

---

src/containers/AddonSettings/VariantSelector.jsx

Settings variant dropdown menu in dev mode shows color-coded badges for production, staging and active development bundles

Enhanced color coding in variant selector dropdown

---

src/containers/CopySettings/ProjectDropdown.jsx
src/containers/ProjectMenu/projectMenu.jsx
src/containers/projectList.jsx
src/pages/UserDashboardPage/UserDashboardPage.jsx
src/services/project/getProject.js

Inactive project are no longer displayed in the project sidebar. 
Only managers and above can see inactive projects in management-related pages, where they are listed at the end of the table and dimmed.

Do not show inactive projects

---

src/pages/UserDashboardPage/UserDashboardPage.jsx
src/services/project/updateProject.js

- Fix: Only show "Create new project" button when there are no projects at all (active/inactive)
- Fix: The projects list UI wouldn't update when a project active flag was updated.
1. Make all projects inactive
2. Ensure the projects can still be accessed on the dashboard overview page.

Fix: When all projects are inactive make sure they stay visible somewhere.

---

src/containers/projectList.jsx
src/pages/ProjectManagerPage/ProjectManagerPage.jsx
src/pages/ProjectManagerPage/ProjectManagerPageContainer.jsx

- Activate and deactivate projects from the context menu when on the projects manager page.
- Only show "Delete Project" once a project is inactive.

enhancement: deactivate project from context menu

---

src/hooks/Tooltip/useTooltip.jsx
src/pages/SettingsPage/AddonsManager/AddonsManager.jsx
src/pages/SettingsPage/AddonsManager/AddonsManagerTable.jsx
src/pages/SettingsPage/AddonsManager/helpers.js

- View and delete broken and crashed addons.
- Add `data-tooltip-no-delay` to invoke a tooltip instantly on hover.
1. Break an addon somehow.
2. Go to addons page and try to remove it.

Highlight broken addon versions

---

src/containers/SettingsEditor/fields.jsx
src/hooks/Tooltip/Tooltip.styled.js
src/hooks/Tooltip/useTooltip.jsx
src/pages/SettingsPage/AddonsManager/AddonsManagerTable.jsx
src/pages/SettingsPage/AddonsManager/helpers.js
src/pages/SettingsPage/Bundles/BundleDeps.jsx
src/pages/SettingsPage/Bundles/NewBundle.jsx

- Tooltips can now accept markdown!
- `data-tooltip-delay` to set the delay for a tooltip
- `data-tooltip-as` to set which tag to be used (`pre`, `markdown`, `div`)
- Fix: dev bundle dep packages would overwrite local change
- Settings field descriptions are now displayed as tooltips.

Improved tooltips

---

src/components/Menu/MenuComponents/Menu.styled.js
src/components/Menu/MenuComponents/MenuItem.jsx
src/components/Menu/Menus/AppMenu.jsx
src/components/RestartBanner/RestartBanner.jsx
src/components/RestartBanner/RestartBanner.styled.js
src/containers/header/AppHeader.jsx
src/containers/header/HeaderButton.jsx
src/context/restartContext.jsx
src/pages/MarketPage/MarketPage.jsx
src/pages/SettingsPage/AddonsManager/AddonsManager.jsx
src/pages/SettingsPage/Attributes.jsx
src/pages/SettingsPage/Bundles/Bundles.jsx
src/services/restartServer.js

- Restart requests are now made server side through the events system.
- The client checks `/api/system/restartRequired` and shows restart banner accordingly.
- The client also subscribes to `server.restart_required` topic for live updates.
- The banner can be snoozed for the rest of the day and will reappear at 8pm.
- Snoozed restarts show a little notification dot on the App Menu.
1. Install/Delete an addon and see if banner appears.
2. Update attributes and see if banner appears.
3. Make a POST request to `/api/system/restartRequired` to see `required=true` and see if banner appears.
4. Click 'snooze' and see if banner hides and notification dot appears.

Restart server banner triggered using a server event

---

src/pages/EditorPage/fields/ToolsField.jsx
src/pages/EditorPage/utils.jsx

- Tools field in editor now shows a readonly dropdown for better readability.
- It also shows the number of tools at the start in brackets.

Tools Field Dropdown

---

src/containers/projectList.jsx
src/pages/UserDashboardPage/UserDashboardPage.jsx
src/styles/index.scss

- Disable "Delete Project" context menu instead of hiding. Thanks @BigRoy

Deactivate to delete project

---

src/components/Details/EntityDetailsHeader.jsx
src/components/ThumbnailUploader/ThumbnailUploader.jsx
src/context/shortcutsContext.jsx
src/pages/EditorPage/EditorPage.jsx
src/pages/EditorPage/NewEntity.jsx
src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardList/UserDashboardList.jsx

- Enhancement: You can now use your keyboard to navigate between folders. Hold shift to selection multiple folders with the keyboard.
- Enhancement: Double click on a folder to  expand/collapse it.
- Enhancement: Hover over a folder with your mouse and press the key `c` to expand/collapse it.
- Enhancement: Hold down `ctrl/cmd` when collapsing a folder to collapse all expanded children.
- Enhancement: When multiple folders are selected, hold down `ctrl/cmd` to expand/collapse all selected.
- Fix: Focus will now return to previously selected folder when open/closing the new folder modal.
- Fix: Hitting esc in the folder modal will now always close it, even when focused on an input.
- Fix: Editor panel height was jumping around.
- Fix: thumbnail upload tooltip.
Depending on how these …

Editor: improved keyboard support and folder collapsing

---

package.json
src/containers/SiteDropdown.jsx
src/pages/EditorPage/EditorPage.jsx
src/pages/EditorPage/EditorPanel.jsx
src/pages/EditorPage/fields/ToolsField.jsx

- **Tool field validation**: Ensured Tools can only be set to null (inherited) or a specific value, preventing empty lists.
- **Tool field dropdown**: Enhanced the dropdown menu to display a clear "Set to Inherit" option.
- **Tools column**: Resolved an issue causing unexpected behavior in the Tools column.
- **Root entity field inheritance**: Fixed a bug where setting a root entity field to null (inherited) wouldn't immediately display the inherited value. A page reload is no longer required.
- **Parent-child field updates**: Optimized the system to update all child entities, not just the first level, when a parent value is changed.

Editor inheriting fixes

---

src/pages/BrowserPage/Products.jsx
src/pages/BrowserPage/ProductsGrid.jsx
src/pages/BrowserPage/ViewModeToggle.jsx
src/pages/EditorPage/EditorPage.jsx
src/services/product/getProduct.js

**Browser**
- Enhancement: Collapsable product groups. Click the group header or hover anywhere over the group and use the shortcut `c`.
- Fix: Disable tile view when multiple folders are selected.
- Fix: sorting products alphabetically by default.
**Editor**
- Enhancement: Expand all child folders using `ctrl/cmd + click` (opposite of collapse all children).
- Fix: Remove `cmd/ctrl+c` shortcut.

Browser grouping and editor enhancements

---

src/components/Menu/MenuComponents/MenuList.jsx
src/components/ProjectButton/ProjectButton.jsx
src/containers/ProjectMenu/projectMenu.jsx
src/containers/header/AppHeader.jsx
src/context/shortcutsContext.jsx

- Enhancement: Full keyboard support using arrows.
- Enhancement: Start typing straight after opening the menu to start searching, there's no need to click the search icon.
- Fix: Search state now clears on close.
- Fix: Block other shortcuts when open, like `s+s`.
- Fix: Ensure the project is always focused when opening. Sometimes it would get stuck on other items.
- Fix: You can now pin **all** projects, if you are a mad man. _[when you pin all the projects](https://www.youtube.com/watch?v=danzsQTDTx4&t=72s)_
I have been thinking about the shortcut to open the projects menu... `1` isn't exactly obvious and maybe something like `m` would be better? This would also have the advantage of freeing up the numbers to be used to select the projects quicker.
You can press `m` then `1` or `2` or …

Projects menu improvements

---

src/components/ListItem/ListItem.jsx
src/components/ListItem/ListItem.styled.js
src/services/userDashboard/userDashboardHelpers.js

Fix: slashes on the path in three areas.

Dashboard tasks path slashes fix

---

src/pages/BrowserPage/ProductsGrid.jsx

Add a count of products and product type icon to the group header.
The original ticket was to add some stacked thumbnails but I think that goes against the aim of decluttering the UI when collapsing.
Set to grid grouped view.
URI: `ayon+entity://demo_Commercial/shots/sh010`

Browser products group header count

---

src/components/status/statusField.jsx
src/components/status/statusSelect.jsx
src/pages/BrowserPage/Products.jsx
src/pages/EditorPage/EditorPanel.jsx

After some discussion it was decided that chevron icon for statuses will only be visible in EditorPanel.
Following changes were implemented:
- chevron visible only for EditorPanel, its possible to add it in other places if property `isChevron` is added (as a `true` bool value)
- chevron itself has `on-surface` (white) color
- font styles of chevron changed to font-variation-settings: `"FILL" 1, "wght" 200, "GRAD" 200, "opsz" 20;`
EditorPanel:
https://github.com/ynput/ayon-frontend/assets/16327908/89f7d071-49f2-4e8a-a139-aa7accec1c10
Browser:

fix: fixed chevron - visible only in EditorPanel

---

package.json
src/components/CommentMentionSelect/CommentMentionSelect.jsx
src/components/Feed/FeedHeader/FeedHeader.jsx
src/components/Feed/FeedReferencePopup/FeedReferencePopup.jsx
src/components/Menu/Menus/UserMenu/UserMenuHeader.jsx
src/components/User/UserDetailsHeader.jsx
src/containers/header/AppHeader.jsx
src/pages/EditorPage/EditorPanel.jsx
src/pages/SettingsPage/UsersSettings/UserList.jsx
src/pages/SettingsPage/UsersSettings/UserTile.jsx
src/pages/SettingsPage/UsersSettings/newUser.jsx
src/pages/TeamsPage/UserListTeams.jsx

This is second part of `UserImage` task. I have updated props of parent components to reflect the fact that `UserImage`  has name and `fullName`, and that only `name` is obligatory prop.
First fix from `ayon-react-components`  is working already for images that have just name property and missing `fullName` (green arrows). This PR is more to fix data flow from parent components and not mix two different properties . 
There is an issue though with some of the images for avatars in `UserImage`, path to them returns no image when I test it. (red arrow) There are more of these cases (orange arrow).
I have also updated version of `ayon-react-components` in `package.json`

fix: fixed props fullName and name passing in UserImage

---

src/components/RefreshToast.jsx
src/context/websocketContext.jsx

If lots of changes were made at a different site then the websocket messages could overload the client.
- Fix: When there are too many messages to handle they will be ignored and you will be prompted to reload the page.
- Hopefully it solves: #303 
1. Open events viewer page.
2. In a new browser, make loads of changes, like creating 1000 folders.
3. The events viewing will probably show the first 10ish and then the toast should appear.
We might need to play with the threshold amount, it's currently pretty low, about 15 changes in one go.

fix: throttle websocket overload

---

src/helpers/checkName.js

- Do not allow `-` or `.` in entity names.
- Only allowed characters are letters (uppercase and lowercase) and underscores `_`.
- Any invalid character/space will replaced with an `_`
✅ `folder_1`
❌ `folder 1`, `folder-1`, `folder.1`, `folder@1` ➡️ `folder_1`

Do not allow "-" or "."

---

src/pages/SettingsPage/Bundles/NewBundle.jsx

**Version NONE** button was fixed in bundles.
`/settings/bundles`
The bundle was being set to `undefined` and then would not be included in the addons object for the PATCH request. Setting the addon version to `null` ensured it was included in the object.
1. Select an addon/s using the mouse or side bar buttons.
2. Click `Version NONE` to set the addon/s version to `NONE`
3. Click save and the version `NONE` should persist.

Version NONE button fix

---

src/pages/SettingsPage/AnatomyPresets/AnatomyPresets.jsx
src/services/anatomy/getAnatomy.js
src/services/anatomy/updateAnatomy.js

Adds a button to unset the primary anatomy preset (revert to built-in).
This PR depends on https://github.com/ynput/ayon-backend/pull/116

Unset primary anatomy preset

---

src/pages/EditorPage/EditorPanel.jsx

🛠️ Fixed tab key behaviour in Editor Panel - tabkey now ignores clierfield button and focus skips to next field
Relates to issue https://github.com/ynput/ayon-frontend/issues/336
https://github.com/ynput/ayon-frontend/assets/16327908/4ba10d84-b7d8-4abf-9b52-c96261785698

fix: added tabindex to skip clearfield when pressing tab

---

src/pages/EditorPage/EditorPage.jsx

- Fix: double clicking a task would try to expand it like a folder. Now it doubling clicking does nothing.

fix: db click only expands folders

---

src/components/ThumbnailUploader/ThumbnailUploader.jsx
src/containers/ThumbnailSimple.jsx
src/containers/thumbnail.jsx
src/pages/BrowserPage/ProductsGrid.jsx
src/pages/ProjectDashboard/panels/ProjectLatestRow.jsx

- added check for falsy values of projectName variable.
- this is aimed to solve issue with creating requests that contained projectName with null value and were flooding Event Viewer with error messages

fix: check if projectName is not falsy (undefined, null) for request

---

src/pages/SettingsPage/UsersSettings/userDetail.jsx

- I have added a simple function that removes any other roles, if the new role is `manager` or `admin`
- there was small caveat - if user is admin he is also a manager. I believe this might be a feature, not a bug so I have adjusted conditions accordingly.
https://github.com/ynput/ayon-frontend/assets/16327908/332f72f0-ebd0-4742-aca3-5c57bf8ad386

fix: remove other roles if user is admin/manager

---

src/components/Details/EntityDetailsPanel.jsx
src/features/context.js
src/pages/BrowserPage/Detail.jsx
src/pages/BrowserPage/RepresentationList.jsx
src/services/entity/entityQueries.js
src/services/entity/getEntity.js

- Fix: representation selection is now stored in the global state and persists across refreshes.
- Enhancement: selecting a representation will show it's details in the panel (like status, tags, etc...).
- Enhancement: you can now right click a representation to see it's full data model.
1. Go to `/browser`.
2. Select a folder.
3. Select a version (in the middle).
4. Select a representation (bottom right).
5. You should see the details for the representation.
6. Right click on the representation and show details modal.

Representations selection and context menu

---

src/pages/EditorPage/EditorPage.jsx

- When a folder with no children had a new child added, folder or task, any changes on the parent folder would be overwritten by the original state.
- Removed broken code that seemingly did nothing else but break.

Editor: Parent folder with 1 new child would overwrite parents changes

---

src/pages/SettingsPage/Bundles/BundlesAddonList.jsx

- replaced icon "upgrade" with info and added more detailed description for tooltip
- Solves this issue: https://github.com/ynput/ayon-frontend/issues/379
Result:

fix: icon type and text fix

---

src/containers/entityDetail.jsx
src/pages/BrowserPage/Detail.jsx
src/pages/BrowserPage/Products.jsx
src/pages/BrowserPage/VersionList.jsx
src/services/ayon.js
src/services/entity/entityQueries.js
src/services/product/getProduct.js

- Fixes a critical issue where the status wouldn't update. See #382 
- Rewrites how the versions data is managed on the products list
- Simplifies some crazy data fetching techniques (what was I smoking a month ago 👁️ )
https://github.com/ynput/ayon-frontend/assets/49156310/84fa288c-0e4b-49cb-b574-89c8b3bb51de
1. Go to /projects/demo_Commercial/browser
2. Click on a version in the middle
3. Change to a different version
4. Change the status on the list item or in the right side panel
fixes #382

fix: version status not updating in browser UI

---

src/pages/EditorPage/EditorPage.jsx
src/pages/EditorPage/EditorPanel.jsx

Inside editor, when a field is set to an empty string `""` then it should be converted to `null` value.
1. Set folder label to something
2. Remove label completely
3. Save changes
4. Check the network tab operations request has label: null

fix: empty strings set to null

---

src/pages/SettingsPage/UsersSettings/UserAccessForm.jsx

Fix: move access groups to under access level

---

src/components/Feed/ActivityDate.jsx
src/components/Feed/ActivityHeader/ActivityHeader.jsx
src/components/Feed/ActivityItem.jsx
src/components/Feed/ActivityVersions/ActivityVersions.jsx
src/components/Feed/ActivityVersions/ActivityVersions.styled.js
src/components/Tooltips/EntityTooltip/EntityTooltip.jsx
src/containers/Feed/Feed.jsx
src/containers/Feed/hooks/useTransformActivities.js
src/containers/ThumbnailSimple.jsx
src/features/dashboard.js
src/pages/UserDashboardPage/UserDashboardTasks/UserDashDetailsFilters/UserDashDetailsFilters.jsx
src/pages/UserDashboardPage/UserDashboardTasks/UserDashDetailsHeader/UserDashDetailsHeader.jsx
src/pages/UserDashboardPage/UserDashboardTasks/UserTasksContainer.jsx
src/services/activities/activityQueries.js
src/services/userDashboard/userDashboardHelpers.js

- New activity item type `version.publish`.
- New filter **Versions** to show only `version.publish`.
- Versions that are made by the same author and within 30 mins of each other are grouped together.
- In the main feed versions are collapsed with a show more button.
https://github.com/ynput/ayon-frontend/assets/49156310/527bdc40-5f16-4692-bcd7-3f8e25896f08
**experimental** viewing **frank stephens** will give some good examples on task **lighting**.

Activity Feed: Versions show in activity feed

---

src/pages/SettingsPage/Bundles/NewBundle.jsx

-   [x] Create new bundles doesn't fail
Cannot assign to read only property 'isDev' error caused by `formData.isDev=...`

fix(bundles): Cannot assign to read only property 'isDev

---

src/components/CommentInput/CommentInput.styled.js
src/components/CommentInput/helpers.jsx

-   [ ] Commenting a file path `D:\\file\to\path` renders as `D:\\file\to\path` with preserved double backslash.
-   [ ] Other uses of `\` to escape characters are preserved.
Comments with `\\` are replaced with `\\\` so that it will render as `\\` when parsed as markdown.
https://github.com/ynput/ayon-frontend/assets/49156310/9b6ed6ad-447f-4d4c-91b0-54617431d24d
Fixes this specific issue with paths but pasting paths could be way more useable. Maybe a path could be "attached" like an image and have actionable features, like copying or even opening file.

fix(comment): \\ replaced with \\\ so that it renders as \\

---

src/containers/header/AppHeader.jsx
src/features/user.js
src/pages/AccountPage/ProfilePage.jsx
src/pages/SettingsPage/UsersSettings/userDetail.jsx

Issue link: https://github.com/ynput/ayon-frontend/issues/335
URL: http://localhost:3000/settings/users
- replaced source of information about user - server instead of redux
- developer mode now appears/disappears without need for refresh
https://github.com/ynput/ayon-frontend/assets/16327908/2b1142e6-9025-4cb2-909f-67f4b7b53c35
close #335

fix: replaced user data source to server for showing developer mode

---

src/pages/SettingsPage/Bundles/Bundles.jsx

-   [ ] Duplicate a bundle that once had a deleted addon (no idea how you know this)
-   [ ] You shouldn't get compatibility error `{addon_name}: {addon_name} {addon_version} is not active`
When duplicating a bundle, ensure that are addons that are now **not** installed are removed from the new bundle.

fix(bundles): ensure only addons that are still installed copy across

---

src/containers/AddonSettings/AddonSettings.jsx
src/containers/AddonSettings/VariantSelector.jsx
src/containers/BundleDropdown.jsx
src/containers/CopySettings/CopySettingsDialog.jsx
src/containers/CopySettings/CopySettingsNode.jsx
src/containers/ProjectDropdown.jsx
src/containers/SettingsEditor/fields.jsx
src/containers/SettingsEditor/widgets.jsx

-   [x] This comment contains a description of changes
-   [x] Referenced issue is linked
To be able to migrate settings including "pinned defaults" we need to have a way how to send "pin information" along with the settings payload without relying on additional endpoints (pinOverride, removeOverride). 
Fortunately for us, set_settings endpoints accept arbitrary dictionaries and not a strict model, so the frontend can send an additional well-known field `__pinned_fields__` along with the payload. This field would be extracted before storing the settings and passed to extract_overrides function on the backend, which will use it to ... do some magic.
Frontend-wise, that **should** be straightforward, we can get this information from the changes table. Existing system of pinning overrides …

Pinning settings using changelist

---

src/containers/Feed/hooks/useCommentMutations.js

`fullName` would be undefined in the patch when creating a new comment. This would cause the new comment author to show as `name` not `fullName`.

Comment: fullName undefined on new comment

---

src/components/MarketAddonCard/MarketAddonCard.jsx
src/components/MarketAddonCard/MarketAddonCard.styled.js
src/pages/MarketPage/AddonDetails/AddonDetails.jsx
src/pages/MarketPage/AddonFilters.jsx
src/pages/MarketPage/MarketAddonsList.jsx

- replaced _install_ with _download_ (and respective word variations)
- implemented in multiple places across addons market (not just button)
- replaced "Not installed" section with "Downloads available" ( since we already have "Updates Available")
- replaced icons `upgrade` or `download_for_offline` with `download`
https://github.com/ynput/ayon-frontend/assets/16327908/d8e8f2a0-237f-4458-9af5-41d52819b934

Market: replaced 'install' with 'download'

---

src/pages/SettingsPage/Bundles/BundleForm.jsx
src/pages/SettingsPage/Bundles/BundleList.jsx
src/pages/SettingsPage/Bundles/Bundles.jsx
src/pages/SettingsPage/Bundles/InstallerSelector.jsx

Fixes an issue where the selection state could become out of sync with internal state, causing the wrong bundle to be archived or deleted.
You can also now archive or delete multiple bundles are once.
1. `/settings/bundles` (s+s shortcut).
2. right click on a bundle and `archive`.
3. right click on an archived bundle and `unarchive`.
4. right click on multiple archived bundles and `delete`.
https://github.com/ynput/ayon-frontend/assets/49156310/563730ec-78dd-4530-a096-995e83c47838

Bundles: fix context selection change for archiving and deleting

---

src/app.jsx
src/components/VersionSelectorTool/VersionSelectorTool.jsx
src/components/VersionSelectorTool/VersionSelectorTool.styled.js
src/containers/Preview/Preview.jsx
src/containers/Preview/Preview.styled.js
src/containers/Preview/PreviewDialog.jsx
src/features/preview.js
src/index.jsx
src/services/activities/getActivities.js

Use the URL search params `preview_id: EntityId` and `preview_type: EntityType` to open the basic shell of the preview dialog.
This is a WIP and just the basis for collaborators work on the components that go inside it.

Web Preview: dialog and state architecture

---

src/components/Actions/Actions.jsx
src/components/status/statusField.jsx
src/components/status/statusSelect.jsx
src/containers/DetailsPanel/DetailsPanel.jsx
src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.jsx
src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.styled.js
src/containers/DetailsPanel/FeedFilters/FeedFilters.jsx

Adds a new prop `isCompact=false` that will hide most of the fields, for a more focused and compact header.
This will be used as part of the preview dialog.

Preview: Details panel header compact mode

---

src/components/AddonCard/AddonCard.jsx
src/components/AddonCard/AddonCard.styled.jsx
src/pages/OnBoarding/Step/AddonSelectStep.jsx
src/pages/OnBoarding/util/OnBoardingContext.jsx
src/pages/OnBoarding/util/OnBoardingStep.styled.js

- added information about version for addons selection
- added spinner (it can take up to few seconds to display addons)
- used title instead of name for addons
- changed 3 columns to two
https://github.com/ynput/ayon-frontend/assets/16327908/efa88d59-ffaa-4878-a6e8-924118ffef46
closes #430

Onboarding: Show addon version when selecting addons

---

src/components/ColumnsSelect/ColumnsSelect.jsx
src/pages/BrowserPage/Products/Products.jsx
src/pages/BrowserPage/Products/Products.styled.js

- Replace Prime react multiselect with arc dropdown.
- Value now defaults to empty array `[]` and will show all columns.
- Fixed issue where clearing would not work.
- Removed "(Single)" and "(Multiple)" as it was just confusing.
- New placeholder "Filter columns..."
https://github.com/ynput/ayon-frontend/assets/49156310/8bec03c2-81da-4237-9493-ad5e73d76fb4

Browser: Columns select dropdown

---

src/pages/EditorPage/NewEntity.jsx
src/pages/EditorPage/NewSequence.jsx
src/pages/EditorPage/TypeEditor.jsx

When selecting a task or folder from a dropdown, the order now matches the order in the anatomy settings.

Type Editor: Dropdown order of folders and tasks now respect settings order

---

src/app.jsx
src/containers/Breadcrumbs/Breadcrumbs.jsx
src/context/uriContext.jsx
src/pages/ProjectDashboard/panels/ProjectLatest.jsx
src/pages/UserDashboardPage/util/useGetTaskContextMenu.js

A project or settings URI could be left over causing a mismatch between the breadcrumbs and page.
On pages that don't have specific URIs use the last part of the URL pathname.
The logic has also been moved to a context provider.
Original problem
Fixed

URI: Fix wrong URI on different pages

---

src/components/FileUploadCard/FileUploadCard.jsx
src/components/FileUploadCard/FileUploadCard.styled.js
src/containers/FileUploadPreview/FileUploadPreview.jsx
src/containers/FileUploadPreview/FileUploadPreview.styled.js
src/containers/FileUploadPreview/mimes/ImageMime.jsx
src/containers/FileUploadPreview/mimes/TextMime.jsx
src/features/context.js

- Support all `text/` mime formats and some custom text formats.
- Use code editor in read only mode for syntax highlighting
- Markdown files preview as rendered markdown.
- PDF files now open in a new tab for previewing.
- `UploadFileCard` now has a consistent UX for pre-viewing and downloading files.
It is now a lot easier to add support for new file types using the object `expandableMimeTypes` in `FileUploadPreview.jsx`
```js
// define expandable mime types and their components
export const expandableMimeTypes = {
image: {
component: ImageMime,
mimeTypes: ['image/'],
fullPreviews: ['png', 'jpg', 'jpeg', 'gif', 'svg', 'webp'],
id: 'image',
},
text: {
component: TextMime,
mimeTypes: ['text/', 'application/json', 'scss', 'jsx'],
id: 'text',
},
pdf: {
component: null,
mimeTypes: ['pdf'], …
```

File Preview: Support for text files and PDFs

---

src/pages/SettingsPage/Bundles/BundleDepsPicker.jsx

- Orders dependency packages options alphabetically desc (z-a) so that the latest packages show first.

fix(bundles): Order dep packages dropdown alphabetically

---

src/pages/BrowserPage/Products/Products.jsx
src/pages/BrowserPage/Products/VersionList.jsx

- Replaces the prime react select component with our own ARC dropdown component.
- Now 16+ versions will provide a search bar.
This whole thing is really weirdly written but I haven't had the time to rewrite it yet. It works so....
1. `/projects/demo_Commercial/browser`
2. Select a folder
3. Select a task and change the version

Browser: Version select replace prime react with arc dropdown

---

src/components/CommentInput/CommentInput.jsx
src/components/CommentInput/CommentInput.styled.js
src/components/CommentInput/hooks/useMentionLink.js
src/components/CommentInput/modules/index.js
src/components/Feed/ActivityComment/ActivityComment.jsx
src/components/Feed/ActivityComment/activityMarkdownComponents.jsx
src/components/Feed/ActivityHeader/ActivityHeader.jsx
src/components/Feed/ActivityReference/ActivityReference.jsx
src/components/Tooltips/EntityTooltip/EntityTooltip.styled.js
src/containers/Feed/Feed.jsx
src/containers/Feed/hooks/useReferenceTooltip.js
src/features/details.js

Reference links inside the comment editor now act the same as they would inside a comment.
- Added reference styling.
- Hover over the reference to see it's tooltip.
- Click on a reference to open the slide out.
- Hitting backspace now delete the whole reference (instead of the just the first character).
- This required creating a new Quill format called `mention`.
- Moved the reference tooltip state to redux so it could be mutated from anywhere (inside quill)
https://github.com/ynput/ayon-frontend/assets/49156310/1139919b-2e52-4ce8-bf17-ad924f09aa96

Comment: reference link styling, deleting and tooltips

---

src/components/MinMaxField/MinMaxField.jsx
src/containers/attributes/attributeEditor.jsx

Instead of `gt, ge, lt, le` values use `min` and `max`.
When `type=float` give the option to toggle `>, ≥, <, ≤`.
The returned attribute can not have both `ge` and `gt` at the same time (same for `lt` and `le`).

Attributes: Min and max values

---

src/components/CommentInput/CommentInput.jsx
src/components/CommentInput/CommentInput.styled.js
src/components/CommentInput/hooks/useMentionLink.js
src/components/CommentInput/quillToMarkdown.jsx
src/components/Feed/ActivityComment/ActivityComment.jsx
src/containers/Feed/Feed.jsx
src/containers/Feed/hooks/useCommentMutations.js
src/containers/Feed/hooks/useTransformActivities.js
src/services/activities/getActivities.js

When a entity is mentioned in a comment, that entities feed has it's cache updated with the changes. This is most obvious when you have two different feeds up at once and one feed mentions the other one.
Also fixes a critical error when trying to edit comments with references in them.
- We can't use `invalidateTags` because sometimes the target feed already has a cursor (from infinite scrolling) and so the refreshed data doesn't get the new comment because it's past the cursor. This is a limitation of RTK Query.
- So instead we need to update the cache manually ourselves. Because we don't know if the target cache exists, which filter it is using then we have to try all the filters.

Feed: mentioning another entity invalidates its feed

---

src/pages/WorkfilesPage/WorkfileDetail.jsx

Root specified with a trailing slash no longer produces paths with a slash duplicated:

Workfiles: fix double slashes when roots are replaced

---

src/components/ListItem/ListItem.jsx
src/containers/Feed/Feed.jsx
src/services/userDashboard/userDashboardHelpers.js
src/services/userDashboard/userDashboardQueries.js

If no task thumbnail is available then it should use the next latest version thumbnail.
I thought versions came sorted from the query but I've added in another sort to be extra sort it's sorting from highest to lowest.
If there is a HERO version with a thumbnail, then that will always be used. 🦸

Tasks: thumbnail does not always use latest version

---

src/features/editor.js
src/pages/EditorPage/EditorPanel.jsx

This was very hard to debug and the issue seemed to happen randomly. My best guess is that states became out of sync because of the debouncing of the changes.
I'm hoping that this fixes the issue by patching the changes to the state instead of overwriting them with all the changes every time. The bad values came from this overwriting method.

Editor: onNewChanges patches rather than overwrites changes

---

src/components/EnableNotifications.jsx
src/pages/AccountPage/ProfilePage.jsx

Disable desktop notifications button and switch when AYON is not hosted over `https` or `localhost`.

Inbox: Disable notifications button if using http

---

src/pages/ServicesPage/NewServiceDialog.jsx
src/pages/ServicesPage/ServicesPage.jsx
src/services/ayon.js
src/services/services/getServices.js
src/services/services/updateServices.js

Better error messages.
- Migrated all queries and mutations to RTK Query.
- Migrated new service dropdowns to ARC dropdowns.

Services: data fetching rewrite

---

src/pages/SettingsPage/Bundles/BundlesAddonList.jsx

Even when versions don't follow traditional semver formating like `0.3.3-dev.2` `0.3.3-dev.1` they should still sort correctly using alphabetical descending.

Bundles: Comparing latest version takes suffixes into consideration

---

src/pages/EditorPage/EditorPage.jsx
src/pages/EditorPage/NewEntity.jsx

This fix ensures that inherited values are not set on children that have some other parent with `ownAttrib`.
https://github.com/ynput/ayon-frontend/assets/49156310/916218a3-dfca-4f85-b4ef-a0622b823038

Editor: Check if indirect child has any parent with ownAttrib

---

src/containers/ProjectMenu/projectMenu.jsx
src/features/dashboard.js

When opening a project, make sure the project is selected when returning home.
If you project was already in the selection, do nothing.
https://github.com/ynput/ayon-frontend/assets/49156310/b9c70edd-e23e-4a27-b8d5-416edd71a32e

Dashboard: keep selected projects in sync with open project

---

src/hooks/useSearchFilter.js
src/pages/BrowserPage/Products/Products.jsx

Before: selecting multiple folders in the browser and then filtering using "search" or "task types" was broken.
After: now you can properly filter even when the versions have been grouped.
Also fixes some type errors that would cause the page to crash.
Before it was incorrectly filtering **after** the grouping, now it does the filtering before the grouping.
1. Go to browser
2. Select multiple folders
3. Search for something like "approved"
4. Filter by task type

Browser: you can now properly filter versions with multiple folders selected.

---

src/containers/Feed/helpers/mergeSimilarActivities.js

Activities should only be merged within a 20 second period. This should deduplicate most user mistakes, for example setting the wrong status and then correcting yourself straight away.
Originally there was no time limit.

 feed only merge activities within 1 minute period

---

src/components/Menu/Menus/HelpMenu.jsx

-   [x] This comment contains a description of changes
-   [ ] Referenced issue is linked
Change the help menu entry label `Graphql Explorer` -> `GraphQL Explorer`.
Apparently it's Graph**QL**
This took me sweat and tears - please accept it[.](https://www.youtube.com/watch?v=N__AkJriaN4)

Help menu label: `Graphql Explorer` -> `GraphQL Explorer`

---

src/containers/CopySettings/CopySettingsDialog.jsx
src/containers/CopySettings/CopySettingsNode.jsx

When project level settings are copied, allow copy "empty values" while displaying the underlying studio-level override

Settings: Fix copying empty project-level values

---

src/services/activities/updateActivities.js

When creating/updating/deleting an activity, now the changes propagate to all "combinations" of selections of that entity.
This was a frontend caching issue.
Everytime an entity or selection of entities is selected a `getActivities(entityIds)` query is made to fetch all activity data for all entities at once.
The FE will create a new cache for every unique `getActivities(entityIds)` request. 
Before we were only patching the comment change for the one cache you were looking at. If you selected a different "combination" of entity ids you could end up with a now stale cache.
Now we make sure to patch every single cache that includes that entityId.

Feed: patch ALL activity caches

---

package.json
src/pages/OnBoarding/Step/AddonSelectStep.jsx
src/pages/OnBoarding/util/OnBoardingContext.jsx

A new bundle is still created, just it won't be set to isProduction.

Bootstrap: Do not create prod bundle if prod bundle already exists

---

src/components/Feed/ActivityComment/ActivityComment.jsx
src/components/Feed/ActivityComment/ActivityComment.styled.js
src/components/Feed/ActivityDate.jsx
src/components/Feed/ActivityHeader/ActivityHeader.jsx
src/components/Feed/ActivityHeader/ActivityHeader.styled.js

- Hover over a date to see the full exact date and time.
- The toolbar now appears over the comment body and not over the time.
https://github.com/ynput/ayon-frontend/assets/49156310/734ecbfa-42e8-4858-85ff-0d7713aef602

Comment: Exact dates and toolbar position

---

src/pages/SettingsPage/SettingsPage.jsx

Addons and bundles should not be accessible to Manager users, the following changes have been implemented:
- removed Addons & Bundles from the settings page nav links
- redirecting to "/" if manager users attempt to access the route directly
closes #597

Authorization: Managers cannot access addons and bundle settings

---

src/containers/VideoPlayer/Trackbar.jsx
src/containers/VideoPlayer/VideoPlayer.jsx
src/containers/VideoPlayer/VideoPlayerControls.jsx

The playhead of the video timeline now grows if number of frames is lower than the timeline width. That makes it easier what portion of the timeline is "occupied" by a frame. If the width is sufficient, frame boundaries are also drawn as well as frame indicator.
Additionally this PR fixes some edge cases in the playback (looping and sync between actual and registered position)
https://github.com/user-attachments/assets/e2102eb1-1fce-4532-b943-f0d3c5a58d0a

Web viewer snap playhead indicator to frame position

---

src/components/ApiKeyManager.jsx
src/containers/Feed/hooks/useUserMutations.js
src/helpers/callbackOnKeyDown.js
src/pages/SettingsPage/UsersSettings/UserAccessForm.jsx
src/pages/SettingsPage/UsersSettings/UserAttribForm.jsx
src/pages/SettingsPage/UsersSettings/UsersSettings.jsx
src/pages/SettingsPage/UsersSettings/newServiceUser.jsx
src/pages/SettingsPage/UsersSettings/newUser.jsx

Existing non service users cannot be converted to Service Users and vice versa. The following actions were taken to avoid that:
- Custom form for service user creation, only username, active/inactive & generated key form fields are required
- Non service users cannot be converted to Service users, option removed from form

Users: Custom form for a adding service user

---

src/components/GridLayout.jsx
src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.jsx
src/containers/Feed/hooks/useTableKeyboardNavigation.ts
src/containers/Feed/hooks/useTransformActivities.js
src/containers/hierarchy.jsx
src/containers/taskList.jsx
src/pages/BrowserPage/Products/Products.jsx
src/pages/BrowserPage/Products/ProductsGrid.jsx
src/pages/BrowserPage/Products/ProductsList.jsx
src/pages/EditorPage/EditorPage.jsx
src/pages/WorkfilesPage/WorkfileList.jsx

You can now use the up and down arrows to change the selection.
Before it would only focus the table row and not select it.
https://github.com/user-attachments/assets/006feb2e-0749-4264-8484-a8413e1f919f
1. http://localhost:3000/projects/demo_Commercial/browser
2. Test each table, folders, tasks, products.
3. Using arrows keys should change selection and update URI.
4. Holding down shift should select multiple.

Browser: keyboard changes selection

---

src/hooks/usePrevious.js
src/pages/SettingsPage/Bundles/NewBundle.jsx

When adding a new bundle, check requests are skipped on add-on path changes. The rest of form changes trigger API checks as expected.
https://github.com/user-attachments/assets/2d3e82ec-f7b1-44a1-be96-305764bbe6fc
closes #589

589 bundles re check of compatibility on path change

---

src/components/Feed/ActivityComment/ActivityComment.jsx
src/components/FileUploadCard/FileUploadCard.jsx
src/containers/Feed/Feed.jsx
src/containers/FileUploadPreview/FileUploadPreview.jsx
src/containers/FileUploadPreview/FileUploadPreview.styled.js
src/containers/FileUploadPreview/hooks/useAttachmentNavigation.js
src/containers/FilesGrid/FilesGrid.jsx
src/features/context.js

Description:
When previewing comment attachments one can navigate through the list via keyboard or mouse.
https://github.com/user-attachments/assets/36672f51-94db-4f43-8da3-5f43bbcb8c6f
closes #604

Comment: Cycling through attachments via keyboard or mouse

---

src/pages/SettingsPage/SettingsAddon.jsx

While testing addon changes in dev iframe doesn't reload content due to caching setup. PR forces new urls on every visit, making sure that iframe content is also refreshed.

Addons: Added senderId to iframe url to always refresh html content

---

package.json
src/components/CommentInput/CommentInput.jsx
src/components/MeOrUserSwitch/MeOrUserSwitch.jsx
src/components/Thumbnail/Thumbnail.tsx
src/components/status/statusSelect.jsx
src/containers/DetailsPanel/DetailsPanel.jsx
src/containers/DetailsPanel/DetailsPanel.styled.js
src/containers/DetailsPanel/DetailsPanelFiles/DetailsPanelFiles.tsx
src/containers/DetailsPanel/DetailsPanelSlideOut/DetailsPanelSlideOut.jsx
src/containers/RepresentationsList/RepresentationsList.jsx
src/pages/ProjectDashboard/panels/ProjectDetails/ProjectDetails.jsx
src/pages/ProjectDashboard/panels/ProjectDetails/ProjectDetails.styled.js
src/pages/UserDashboardPage/UserDashboardTasks/DashboardTasksToolbar/DashboardTasksToolbar.jsx
src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardKanBan.jsx
src/services/activities/updateActivities.js

- Watchers: invalidate cache when new comment created so that bell icon is updated to show you are a new watcher.
- Panel: Close button now works on slide out and is hidden when not enabled.
- Representations: disable the slide out until there is a better solution.
- Status Select: Selecting multiple statuses now has the correct position for message `x Selected`.
- Overview: Remove project thumbnail image.
- Tasks: me or assignees now uses all assignees to avoid issues moving across projects.

Global: Bugs cleanup

---

src/api/rest.ts
src/app.jsx
src/pages/LauncherAuthPage/LauncherAuthPage.tsx
src/pages/LauncherAuthPage/index.ts
src/pages/LoginPage/LoginPage.jsx
src/services/auth/getAuth.js

Launcher authentication

---

src/components/Feed/ActivityGroup/ActivityGroup.jsx
src/components/Feed/ActivityItem.jsx
src/components/Feed/ActivityStatusChange/ActivityStatusChange.jsx
src/components/Feed/ActivityStatusChange/hooks/getContextParents.js
src/containers/Feed/helpers/mergeSimilarActivities.js
src/containers/Feed/hooks/useTransformActivities.js

Showing detailed version info in status change activities depending on selection context
* displaying folder/task name on activity status change items when focused 
* product name included on version selection
* folder name included if multiple selected
* reverted change  that introduced bug which removed activity status icons
https://github.com/user-attachments/assets/f55c1513-42c1-4224-9cfe-3467d2942e60
closed #665

Activities: feed cannot identify status changes for multiple selected folders/tasks/versions

---

src/helpers/url.ts
src/pages/MarketPage/AddonDetails/AddonDetails.jsx
src/pages/MarketPage/AddonDetails/AddonDetails.styled.js

Adding links tag to addon details section in Addon Market page
Closes #704

Market: Show addon links

---

src/containers/hierarchy.jsx

Multiple components depending on setUri context change call their own dispatches which created a race condition issue, where expanding folders cancel the selection changed callback.
To fix it we're enqueuing the setUri dispatch within the onSelectionChange callback.
https://github.com/user-attachments/assets/304c081c-2d87-47f0-8913-84d8ad376164
Closes #716

Hierarchy: Fix conflicting selection events

---

src/pages/SettingsPage/Bundles/Bundles.jsx

Checking that bundle list is not empty before pushing to selected bundles list it's first item name.
Closes #748

Bundles: Fixing error on navigating to bundles page when no bundles exist

---

src/pages/EditorPage/EditorPage.jsx

The name field had changed to `field="labelThenName"` and so it didn't match `name` in all columns. Now the columns filter uses the key value of the column instead of the field.

Editor: Use 'key' to filter columns instead of props.field.

---

src/pages/SettingsPage/Bundles/Bundles.jsx

Production bundle selected by default - or first if non is production is not affected by bundleList changes. This fixes the issue raised, where setting any other bundle to staging would reset the original selection
https://github.com/user-attachments/assets/b1bfb970-4cc4-46c4-ac57-f24ce4907602
Closes #755

Bundles: Initial bundle selection is not influenced by bundleList changes

---

package.json

- Fixes an issue where the ColorPicker dialog was too small. Now it sizes correctly.
- Root fix in ARC -> https://github.com/ynput/ayon-react-components/commit/2d097cbbf02116f9a00c047dcfba2d8c4b644b8d

Settings: Color Picker dialog size broken in settings

---

src/pages/UserDashboardPage/UserDashboardNoProjects/UserDashboardNoProjects.styled.js
src/pages/UserDashboardPage/UserDashboardNoProjects/UserDashboardNoProjects.tsx

Non admin/manager users cannot create projects, the "create new project" button was removed.
Also applied minor styling changes.
Closes #753

Dashboard: Create project button removed for normal users 

---

src/containers/DetailsPanel/helpers/getEntityPathData.ts

Breadcrumbs segment data was using the product id instead of the version id for its last segment.
https://github.com/user-attachments/assets/dba556af-ffa4-4632-b9aa-e45e98bb4c05
Closes #782

Entity Path: Populating correct version id in breadcrumb segments data

---

src/features/project.js

I'm pretty sure that VDBs published from Houdini and Maya do not show the relevant `vdb` icon because the product type is `vdbcache` and not `vdb`. So this refactors the hardcoded icon to match `vdbcache` name.
I did not test this. :)
Also see: https://github.com/ynput/ayon-traypublisher/pull/13
No idea whether changing this may affect anything else.

Update product type `vdb` to `vdbcache` name for icon

---

src/pages/SettingsPage/Bundles/NewBundle.jsx

When adding a new bundle, the effect listening to addon version changes was triggering another form update which resulted in overwriting the the form name/installer version to its defaults. Addon changes are not really needed, we're removing them.
https://github.com/user-attachments/assets/35287f59-8416-48f4-b7c8-a178200f2c19
Closes #785

Bundles: Avoiding form reset on bundle addon version changes

---

src/containers/TasksProgress/components/FolderBody/FolderBody.tsx
src/containers/TasksProgress/helpers/formatTaskProgressForTable.ts
src/containers/TasksProgress/helpers/useFolderSort.ts

Handles the situation where a task is inside of a root folder.
The folder row was not showing because it never had a parent folder (because it would was in the root).
This fix places the root folder outside of any grouping.

Tasks Progress: Tasks inside root folders

---

src/components/AddonDialog/AddonDialog.jsx
src/pages/SettingsPage/AddonInstall/AddonInstall.jsx
src/pages/SettingsPage/AddonInstall/AddonUpload.jsx
src/services/queryUpload.js

When uploading installers/addons, whenever the upload dialog is closed, an abort signal is sent to axios, stopping the upload.
https://github.com/user-attachments/assets/5a5a7996-8b18-47d0-949a-234753d0a9d6
closes #733

Bundles: Cancelling file upload on window close

---

src/containers/DetailsPanel/DetailsPanelSlideOut/DetailsPanelSlideOut.jsx
src/containers/Viewer/Viewer.styled.ts
src/containers/Viewer/ViewerDialog.tsx

Inside of the viewer (review)...
- Slide was hidden by an `overflow: hidden;`
- Pressing `Escape` now closes the slide out first instead of closing the whole dialog.

Viewer: Slide out not showing

---

src/components/Feed/ActivityComment/ActivityComment.tsx

Comments are hidden now while editing comments.
https://github.com/user-attachments/assets/afcdc4e1-d8da-4a34-bb80-78a5b19887fc
Closes #836

Reactions:  Reactions stay hidden while editing comment

---

src/hooks/useAddonContextResend.ts
src/pages/ProjectAddon.jsx
src/pages/SettingsPage/SettingsAddon.jsx

Project/Settings addon pages now listen to 'request_context' messages and push context accordingly.
The avoids addon errors due to missing context information.

Addons: Fixed missing context issues, style improvements

---

src/containers/FileUploadPreview/FileUploadPreview.jsx
src/containers/Viewer/ViewerDialog.tsx
src/features/context.js

Added extra overlay to capture clicks outside content / arrow components, closing previewer when clicked.
Pressing escape while in preview mode no longer propagates event.
https://github.com/user-attachments/assets/a8f74938-51d6-426a-bd31-797b6ffbd5a0
Closes #835

Previewer: Closing preview modal when clicking outside content/nav arrows.

---

src/containers/Viewer/Viewer.tsx

Payload param statePath was missing when dispatching updateDetailsPanelTab action
https://github.com/user-attachments/assets/0e5c685d-49cf-48a7-8c60-590f4ab19fe5

Viewer: Fixed error on add reviewable button click

---

src/containers/DetailsPanel/DetailsPanelFloating/DetailsPanelFloating.tsx

- Fix the users query so that every user (not just admins) can see the users.
- Skip queries if the PiP is not open.
- The graphql query `users` is not accessible by regular users so the rest endpoint for project users is required.
1. Log in as a regular user
2. Open a pip with assignees
3. Check assignees still show in pip
4. Check logs for any queries that fail related to the pip

PiP: users query all users can access

---

src/containers/Watchers/Watchers.tsx
src/pages/TasksProgressPage/TasksProgressPage.tsx
src/services/watchers.ts

Whenever the watchers for a task updates it should invalidate the caches for any versions watchers.
Based on this BE logic: https://github.com/ynput/ayon-backend/pull/398/files
https://github.com/user-attachments/assets/1444b40f-4ff1-4bfd-9b82-a7ebddc6ceb7
It's a bit annoying that every versions watchers cache is invalidated and not just the versions for the task, but I think this is a worthwhile tradeoff to keep things simple. There are usually no more than 3 version caches around at anyone time anyway.
1. Open a task to see the watchers and then open a version on the task to see those watchers.
2. If the watchers on the task changes then the watchers on the versions should also update.
3. Watcher changes on the version does NOT affect the task watchers, only task -> versions link.
4. If …

Watchers: Invalidate versions watchers when changing tasks watchers

---

src/components/InstallerDownload/InstallerDownloadPrompt.jsx
src/containers/ReleaseInstallerDialog/ReleaseInstallerPrompt/ReleaseInstallerPrompt.styled.ts
src/containers/ReleaseInstallerDialog/ReleaseInstallerPrompt/ReleaseInstallerPrompt.tsx
src/containers/ReleaseInstallerDialog/components/Card.tsx
src/containers/ReleaseInstallerDialog/forms/ReleaseInstallerOverview.tsx
src/containers/ReleaseInstallerDialog/helpers.ts
src/containers/header/AppHeader.jsx

When no installers or dependency packages are installed then this prompt will show.
Clicking on the prompt will open the **Install pipeline release** dialog.
The aim is to help direct new admins to set up the pipeline for the first time.
This new prompt will be reference by a new tutorial called **Pipeline setup**.
- Improved the mandatory buttons inside **Install pipeline release** dialog to say "Pick {items}" rather than just "Change".
- "Pick Addons" button shows when only mandatory addons have been selected.
1. Ensure the server has no installers or packages.
2. Ensure user logged in is an admin.
3. Click on setup pipeline prompt and install release modal should open.
4. After install release is finished and the server has restarted the prompt should not show.
5. Dismissing the prompt …

Onboarding: Setup pipeline prompt

---

src/app.jsx
src/pages/ProjectDashboard/DashboardAddon.jsx
src/pages/UserDashboardPage/UserDashboardPage.jsx
src/services/addons/getAddons.ts

Addons can now show in the dashboard if they have the "dashboard" scope. This is useful for addons that do not always have a specific project, for example studio planning #819 .
Something on the BE might need to be implemented @martastain?

Dashboard: Show addons that are scoped to dashboard

---

src/containers/SettingsEditor/FormTemplates/ObjectFieldTemplate.tsx
src/containers/SettingsEditor/SettingsEditor.sass
src/containers/SettingsEditor/Widgets/DateTimeWidget.tsx
src/containers/SettingsEditor/Widgets/SelectWidget.tsx

Form fields stretch as much as possible up to 800px, included date fields and selectors
https://github.com/user-attachments/assets/d1c23976-b7cd-4dbe-8f38-8aa408deee73

fix(Settings): Aligning form fields in settings pages

---

src/containers/TasksProgress/TasksProgress.tsx
src/containers/TasksProgress/components/FolderBody/FolderBody.tsx
src/containers/TasksProgress/components/TasksProgressTable/TasksProgressTable.tsx
src/containers/Viewer/Viewer.tsx

- Selecting a folder on the progress page and hitting the spacebar should open the folder in the viewer.
https://github.com/user-attachments/assets/1874a420-acd7-46aa-af14-fad4976f96d7
- Fixed a bug where opening the viewer with no specific reviewableId (folder/product) would not auto-select the first reviewable if it was "conversion recommended". This would result with no reviewable selected and an empty video player.

Task progress: spacebar to open selected folder

---

src/pages/SettingsPage/Bundles/BundleDetail.jsx
src/pages/SettingsPage/Bundles/BundleList.jsx
src/pages/SettingsPage/Bundles/Bundles.jsx

Remove set production and set staging shortcuts on bundles as it could be dangerous.
https://community.ynput.io/t/site-settings-shortcut-issues

Bundles: Remove bundle status shortcuts

---

src/context/shortcutsContext.jsx
src/hooks/useShortcuts.js

The shortcuts were not being properly removed when switching pages causing odd behaviours. It was possible to trigger a shortcut action of a completely different page.
This was due to a stale setState method.
https://community.ynput.io/t/site-settings-shortcut-issues

critical: Shortcuts were not being unmounted when moving pages

---

src/pages/SettingsPage/AnatomyPresets/PresetList.jsx

This PR removes the "Version" column from the Anatomy Presets table. The column was originally intended to track the version of the anatomy model associated with presets, but it has caused confusion because it is not relevant for direct preset versioning.

Removed version column from anatomy presets list

---

src/pages/SettingsPage/UsersSettings/UserLicenseForm.tsx
src/pages/SettingsPage/UsersSettings/userDetail.jsx

Selecting multiple users and changing one value would affect all values even if they were mixed. You could change one field and then an untouched field would be overwritten to one value for the selection. This could be dangerous as use permissions were part of this.
Now only fields that have been "touched" are updated, leaving alone fields with mixed state.
https://github.com/user-attachments/assets/2acda30b-d8cc-41f1-9447-e16273a7bc2a
Select many users with different levels. Now change the guest switch and save. All selected users should have the same guest value but all other value, included level, should remain the same for each user.

Users: updating multiple users respects mixed fields

---

src/api/rest/inbox.ts
src/pages/InboxPage/Inbox/Inbox.jsx
src/pages/InboxPage/hooks/useUpdateInboxMessage.ts
src/services/inbox/updateInbox.ts
src/services/project/ProjectTypes.ts
src/services/project/getProject.ts

Clear all button on the inbox page will clear all messages even if they have not been loaded yet.
[REQUIRES ynput/ayon-backend/pull/498 on the server]
1. Create over 100 inbox items for multiple projects.
- This is to ensure we have messages from other projects that are never loaded onto the page.
2. Clicking "Clear All" should remove all messages.
3. Refresh to ensure all messages have actually been cleared.
Uses the new endpoint argument `all` on updateInbox query to apply those changes to all inbox items. This is still on a per-project level so we must do run this query for every project to ensure all messages from all projects are updated.

Inbox: Clear all, clears all messages (not just ones on screen)

---

src/components/CommentInput/CommentInput.jsx
src/components/CommentInput/hooks/useAnnotationsSync.ts
src/components/Feed/ActivityComment/ActivityComment.tsx
src/containers/DetailsPanel/DetailsPanel.jsx
src/containers/DetailsPanel/DetailsPanelFloating/DetailsPanelFloating.tsx
src/containers/Feed/Feed.jsx
src/context/FeedContext.tsx
src/features/viewer.ts

- Fixes a bug that would crash the window when editing a comment and then drawing an annotation.
- Only one comment is editable at once now.
- You can now add annotation attachments to previous comments by going into editing mode and drawing on the canvas.
https://github.com/user-attachments/assets/c94569a7-ad0a-4d69-ba02-cb9c28408cb7

Feed: Editing 1 comment and adding drawings to comments

---

gen/openapi-config.ts
src/api/rest/market.ts
src/api/rest/releases.ts
src/components/AddonsSelectGrid/AddonsSelectGrid.tsx
src/components/MarketAddonCard/MarketAddonCard.tsx
src/components/Powerpack/PowerpackButton.tsx
src/components/Powerpack/PowerpackDialog.tsx
src/components/PricingLink.tsx
src/components/Release/ReleasePreset.jsx
src/components/Release/ReleasePreset.styled.js
src/components/SubChip/SubChip.tsx
src/constants/index.ts
src/containers/ReleaseInstallerDialog/forms/ReleaseInstallerAddons.tsx
src/containers/ReleaseInstallerDialog/forms/ReleaseInstallerOverview.tsx
src/containers/ReleaseInstallerDialog/hooks/useReleaseInfo.ts
src/containers/Slicer/SlicerDropdown.tsx
src/pages/MarketPage/MarketAddonsList.tsx
src/pages/MarketPage/MarketDetails/AddonDetails.tsx
src/pages/MarketPage/MarketDetails/ReleaseDetails.tsx
src/pages/MarketPage/MarketFilters.tsx
src/pages/MarketPage/MarketPage.jsx
src/pages/OnBoarding/Step/AddonSelectStep.tsx
src/styles/index.scss

- Uses market v2 model https://github.com/ynput/ayon-backend/pull/509
- New "free" filter
- Subscribe button for addons not avaliable
- Pro/Studio chip to show if the addon requires a subscription.

Market: Use V2

---

src/containers/SettingsEditor/Widgets/TextWidget.tsx

Disables yellow outline around text fields if the value is 'initialized' yet does not match the current text fields value.
This seems to be confusing the users often, without actually representing an issue.
Fix #593
This may actually be hiding another issue because we may just be invalidly doing the comparison on whether something matches the value or not (e.g. `null` versus empty strings or alike?)
Do we just want to avoid setting the border for now? Or actually figure out why we're flagging some text widgets?

Disable `1px solid yellow` outline for text widgets

---

src/hooks/useUserProjectPermissions.ts

Fix typo: `AllProjectsPremissions` -> `AllProjectsPermissions`
Code cosmetics
For those who can't unsee it.

Fix typo: `AllProjectsPremissions` -> `AllProjectsPermissions`

---

src/containers/VideoPlayer/VideoPlayer.jsx
src/containers/Viewer/Viewer.styled.ts
src/containers/Viewer/ViewerImage.tsx
src/containers/Viewer/hooks/useViewerAnnotations.ts

- pass container dimensions (width/height) to `AnnotationsCanvas` instead of passing the `containerRef`, as per the new Power Pack version requirements
- use the actual media dimensions (i.e. video frame size and original image size) for the `AnnotationsCanvas`
- set the `ViewerImage`'s `<img>` to `display: block` - gets rid of extra space at the bottom
- remove 2px offset for the video viewer - we believe this is no longer needed and makes the canvas fit perfectly on top of the video
- we are not 100% sure why the 2px offset was needed previously. We haven't been able to reproduce any issues once the offset was removed.
- canvas compositing can now take a while for larger images. This causes noticeable lag while the annotated thumbnail is being generated. To be addressed separately. …

Annotations: pass dimensions correctly for the upcoming new Power Pack version

---

src/pages/UserDashboardPage/UserDashboardTasks/DashboardTasksToolbar/DashboardTasksToolbar.jsx
src/services/auth/getAuth.js

Force assignees filter to "me" when user has no permissions to list other users (and hence the `MeOrUserSwitch` component is hidden to switch it manually)
This seems to work, but this might need a `useEffect`?
```jsx
useEffect(() => {
if (!isManager && assigneesFilter !== "me") {
console.log("Force assignees filter to me")
setAssignees({
assignees: [],
filter: "me"
})
}
}, [assigneesFilter, isManager])
```
Fix https://github.com/ynput/ayon-frontend/issues/1030

Dashboard: Force assignees filter to "me" when user has no permissions to list users

---

src/containers/Viewer/Viewer.styled.ts
src/containers/Viewer/ViewerImage.tsx
src/containers/Viewer/index.ts

- adds some extra styling to the `ViewerImage` component so portrait images are viewed correctly
- also added overflow: hidden to the container, so that the surrounding UI isn't overlapped.
before:
after:

Viewer: display images with portrait aspect ratios correctly

---

src/components/LicensesDialog/LicensesDialog.tsx
src/pages/SettingsPage/UsersSettings/UsersOverview.tsx

If your instance is using license pools, show a useful total of licenses consumed and available.

Users: Show total license used

---

src/pages/SettingsPage/ServerConfig/ServerConfig.tsx
src/pages/SettingsPage/ServerConfig/ServerConfigUpload.tsx

Toggle the upload component to "Remove" button if it currently contains an uploaded file so that you can remove things.
@Innders visually it looks good - but I can't get the _clear_ to actually influence the stored result. So when refreshing you can see it never actually 'cleared' anything.
Fix #1036

Global Customizations: Allow to remove an uploaded image

---

src/context/viewerContext.tsx
src/remote/useLoadModule.ts

When an addon version remote module is not compatible with the server, prevent it from from loading and show warning. 
The remote modules will not load and use the fallback code (default behaviour).
1. Test with FE `1.7.3`.
2. Have powerpack `0.0.1` installed.
3. Open a reviewable in the viewer.
4. A warning toast should appear.

Modules: Set min required version for remote load

---

src/containers/AddonList.jsx
src/containers/SettingsEditor/FormTemplates/FieldTemplate.tsx
src/containers/SettingsEditor/FormTemplates/ObjectFieldTemplate.tsx
src/helpers/copyToClipboard.js

Due to missing "props.formData" dependency in useMemo for context menu items, copy function didn't work properly on arrays.
This is now fixed. Additionally a warning is now displayed if there's nothing to copy.
- Right after page loads, find a setting of type `list[SomeSubModel]` in normal (collapsible) layout
- Copy the entire array by right-clicking the panel header
- paste the data somewhere
Note: This worked before when you switched to another addon and back, but not after page load.

Settings: fix array copy in settings

---

src/pages/LoginPage/LoginPage.jsx
src/pages/LoginPage/LoginPage.styled.jsx

- Ability to show the logo even if there is no MOTD
- Always shows the logo full width and max 100% height.
We made this change so that by default the logo could in theory fill the entire space giving the uploader more control over the size of the logo.
**Before**: The logo was capped at max 60px height making it very small. It would only work well be very wide logos.
**After**: The logo fills all the space, im this case the logo becomes too big but we have a solution for that.
**Size control**: Now we can control the size of the logo by adding horizontal margin. The more margin added, the smaller the logo.

Login: Logo shows without text and full width and height

---

src/components/Feed/ActivityVersions/ActivityVersions.jsx
src/components/Feed/ActivityVersions/ActivityVersions.styled.js
src/containers/Feed/helpers/groupActivityVersions.js
src/services/activities/activityQueries.js

Show version comment on the version activity in the activity feed
Show `version.attrib.commen` on the version activity in the activity feed
I moved the version number to after the product name, because otherwise the layout looked very odd.
Plus it matches visually with how we're display product+version on the breadcrumbs in the entity sidecard, like here:
Fix https://github.com/ynput/ayon-frontend/issues/778
Before:
After:
---
Without comment:
Before:
After:

Show version comment on the version activity in the activity feed

---

src/context/websocketContext.jsx

Sometimes the access token can get cleared. This won't log the user out as they still have the cookie but the websocket will fail to connect and continue to keep trying to connect. This will cause a restart screen every 5 seconds (everytime ws tries to connect).
Now when the WS can not connect we check for an accessToken in localstorage and if there isn't one then we log the user out.

Auth: Better handle WS disconnect

---

src/containers/ReleaseInstallerDialog/ReleaseInstaller.tsx
src/containers/ReleaseInstallerDialog/helpers.ts
src/pages/SettingsPage/Bundles/getNewBundleName.js

The new bundle created by the pipeline updater should be named with the release version not release name or "Bundle" if there is no name for any reason.
This ensures that the release suffix "kitsu", "ftrack", "shotgrid" is not included in the bundle name.

Pipeline Updater: Bundle name uses studio name or "Bundle"

---

src/containers/SettingsEditor/Widgets/SelectWidget.tsx

Sometimes you just want to select all of the options for enum field in the settings. This is super annoying if there are lots of items to select.
This PR adds the "Select all" button if there are more than 10 options and the dropdown is multi-select.

Settings: Select all option for dropdowns with more than 10 options

---

src/components/ActionsDropdown/ActionsDropdown.jsx
src/containers/Actions/Actions.jsx
src/containers/Actions/Actions.styled.js
src/containers/DetailsPanel/FeedFilters/FeedFilters.styled.js
src/hooks/useActionTriggers.ts

The client can now handle web actions to perform different tasks.
When these key value pairs are present in the payload of an action response they will trigger different actions on the client.
```ts
interface QueryParams {
[key: string]: string
}
interface ActionPayload {
__queryParams?: QueryParams // adds query params to the URL
__navigate?: string // navigates to a different page
__download?: string // triggers a file download from a relative URL
__copy?: string // copies string content to clipboard
}
```
Example of an action definition in an addon.
```python
navigate_url = "/dashboard/tasks"
return await executor.get_server_action_response(
message=f"Navigating to: {navigate_url}",
__navigate=navigate_url
)
```
Here is an example of a web action being used to set some query parameters …

Actions: Client side triggers

---

src/components/NewEntity/NewEntity.tsx
src/context/NewEntityContext.tsx
src/pages/ProjectOverviewPage/ProjectOverviewPage.tsx

- Fix: When creating new entities the slicer folder selection is now taken into account. Use the slicer to select a folder you want to create an entity in.
- Fix: Attach path to new entity patches so that they work with slicer filtering (otherwise they won't show).
- Fix: Disable create entity when not in show hierarchy mode.
- Improvement: Slicer attributes will now be added to new tasks. For example if you are filtering by assignees, those assignees will be automatically added to the new task.
https://github.com/user-attachments/assets/6346f355-e8a0-4354-8665-137c31b5cae9
_Creating a new task with an assignee_

Overview: New entities respect slicer selection

---

src/services/entity/updateEntity.js
src/services/overview/getOverview.ts

When updating a folder in the details panel the optimistic updates wouldn't take inheritance into consideration.
Because the details panel updating logic is completely detached from the overview it was very hard to calculate the changes on the client.
The solution for now is to invalidate the overview queries so that the fresh inheritance data if fetched.

Overview: Updating details panel folders will invalidate queries

---

shared/src/ProjectTreeTable/context/ProjectTableContext.tsx
shared/src/hooks/useLocalStorage.ts
src/containers/TasksProgress/helpers/formatSearchQueryFilters.ts
src/pages/ProjectOverviewPage/containers/SearchFilterWrapper.tsx
src/pages/ProjectOverviewPage/context/ProjectOverviewContext.tsx

Fixes an issue where the local storage state would not update it's stored value when changing it's key. This resulted in seeing the same filters for all projects, even when they had different filters set.

useLocalStorage key updates

---

src/pages/SettingsPage/Bundles/CopyBundleSettingsDialog/CopyBundleSettingsDialog.tsx

This pull request modifies the `CopyBundleSettingsDialog` component to improve the handling of `sourceVariant` and `targetVariant` values in the `migrateBundleSettingsRequest` object.
When specifying dev bundle, variant must equal to the bundle name.
There's an additional (optional) backend PR that performs a sanity check and returns an error when there's a mismatch.
https://github.com/ynput/ayon-backend/pull/588

Fix: Copy settings from dev bundle

---

shared/src/hooks/useScopedStatuses.ts

If status scope is null (which may happen when importing an old project, it should be considered as "all entity types" instead of crashing the page. Empty list should be considered as a status that is not shown at all.

Allow null status scope

---

shared/src/components/EntityPath/EntityPath.styled.ts
shared/src/components/EntityPath/EntityPath.tsx

Sometimes even after some of the path segments are collapsed, the resulting path is still too wide to fit inside the panel width. This PR adds an extra layout effect which truncates the last segment's text to compensate for this.
It's possible sometimes the reduction will over-correct, because I wanted to avoid calculating the exact remaining path width again - I'm just using the current width at the time when the layout effect runs.

Truncate last path segment in DetailsPanel to avoid panel width being affected

---

shared/src/containers/Actions/Actions.tsx

Use group label of webactions in actions combobox and tooltip.
Group label was added to action manifest but UI did not respect which makes the attribute unusable.
Resolves https://github.com/ynput/ayon-frontend/issues/1152

Webactions: Use groupLabel if available

---

shared/src/containers/ProjectTreeTable/context/ClipboardContext.tsx
shared/src/containers/ProjectTreeTable/context/clipboard/clipboardUtils.ts
shared/src/containers/ProjectTreeTable/widgets/CellWidget.tsx
shared/src/containers/ProjectTreeTable/widgets/DateWidget.tsx

This pull request introduces several changes to improve the handling of clipboard data, date values, and unrecognized types in the `ProjectTreeTable` component. The key updates include allowing empty clipboard text, refining how empty or invalid values are processed, and adding safeguards for unrecognized data types.

Fix: overview cannot copy empty array and clear field option

---

shared/src/containers/Feed/context/FeedContext.tsx

This PR fixes a bug in the mention tooltip data fetching, that used the feed context entity type instead of the type of the hovered mentioned entity. That caused malformed requests and log flooding in the case when for example mentioned user tooltip was displayed in the version entity feed and data for `version id=username` was requested.

Fix fetching tooltip data for mentions

---

shared/src/components/Thumbnail/StackedThumbnails.tsx
shared/src/components/Thumbnail/Thumbnail.styled.ts

The details panel thumbnail now uses the contain object fitting so that the full image is always visible.
16/9 images will always fit perfectly while other ratios will have black bars.
https://feedback.ayon.app/p/11square-thumbnail-size-support

Details Panel: Details panel thumbnail uses contain

---

src/pages/ProjectPage/ProjectPage.tsx
src/pages/UserDashboardPage/UserDashboardPage.jsx

This pull request introduces role-based access control for add-ons in both the `ProjectPage` and `UserDashboardPage` components. It ensures that only users with the appropriate roles (`isAdmin` or `isManager`) can access certain add-ons. The changes also include some minor code refactoring to support this functionality.
`admin` and `manager` flags are supported since forever, but added to FrontendScopeSettings typeddict on the server in https://github.com/ynput/ayon-backend/pull/606

Hide admin addon frontends to non admins (configurable)

---

shared/src/containers/Feed/Feed.tsx
shared/src/containers/Feed/components/ActivityComment/ActivityComment.tsx
shared/src/containers/Feed/components/CommentInput/CommentInput.tsx
shared/src/containers/Feed/components/CommentInput/helpers.tsx
shared/src/containers/Feed/components/CommentInput/hooks/useAnnotationsSync.ts
shared/src/containers/Feed/components/CommentInput/hooks/useAnnotationsUpload.ts
shared/src/containers/Feed/components/FileUploadCard/FileUploadCard.styled.ts
shared/src/containers/Feed/components/FileUploadCard/FileUploadCard.tsx
shared/src/containers/Feed/components/FilesGrid/FilesGrid.tsx
shared/src/containers/Feed/helpers/mergeAnnotationAttachments.ts
shared/src/containers/Feed/hooks/useCommentMutations.ts
shared/src/containers/Feed/hooks/useTransformActivities.ts
shared/src/containers/Feed/index.ts
shared/src/context/DetailsPanelContext.tsx
src/pages/ProjectListsPage/context/ListsModulesContext.tsx

The DetailsPanel component now handles annotations in a smarter way. Annotations are saved as 2 separate files - composite and transparent, alongside a bit of metadata that lets us reconstruct the annotation as necessary.
When Activities are loaded, the files which belong to the same annotation are "merged" and presented as a single attachment. This attachment then has the ability to jump to the video frame where the annotation range starts. Also, the DetailsPanelContext now exposes a `feedAnnotations` array which lets the consumer app display all the annotations currently in the feed.

Annotations storage improvements

---

shared/src/containers/Feed/Feed.tsx

With the Feed component now exposing a list of all annotations shown in the comments, there's an edge case where if the feed is actually empty, the annotations list stays set from the previous state of the feed.
This PR makes it so the annotations list is cleared if no activities are found in the feed.

Feed: clear feed annotations array if no activities found in feed

---

shared/src/containers/Feed/Feed.tsx
shared/src/containers/Feed/components/ActivityComment/ActivityComment.tsx
shared/src/containers/Feed/index.ts

In order for UIs using the DetailsPanel to see which annotations are associated with which activities (e.g. to highlight them from the outside), we need to add the `activityId` to each annotation.
We also highlight the activity if an annotation is jumped to from the FileUploadCard.
I added the `activityId` as an optional field so it shouldn't clash with anything.

Add activity IDs to feed annotations and highlight activities on annotation click

---

shared/src/containers/Feed/components/ActivityComment/ActivityComment.tsx
shared/src/containers/Feed/components/CommentInput/hooks/useAnnotationsSync.ts
shared/src/containers/Feed/components/FileUploadCard/FileUploadCard.styled.ts
shared/src/containers/Feed/components/FileUploadCard/FileUploadCard.tsx
shared/src/containers/Feed/components/FilesGrid/FilesGrid.tsx

- fixed a wrong offset when skipping to the annotation's frame
- if a comment attachment is an annotation, we now don't show the file name. Instead, we show a small annotation icon and the frame range
- for an unsaved annotation, instead of just passing a boolean `isUnsavedAnnotation` to `FileUploadCard`, we pass all the annotation data. This way, even unsaved annotations can show the range instead of file name.

Improve how annotations are displayed in the Feed

---

src/context/UriContext.jsx

Fixes a type error where representations was removed in the focused array but it still accessed by a findLast function causing a silent error and the uri navigation to fail.
Updates to remove faulty key and also use new logic that means it won't error if the key not longer exists.

URI: Navigation not correctly going to focused entity in browser page 

---

shared/src/api/queries/overview/updateOverview.ts
src/components/NewEntity/NewEntity.tsx
src/services/tasksProgress/getTasksProgress.ts

We now properly invalidate the correct tags for task progress and user dashboard to ensure they are always up to date with the overview.

overview: Fixed an issue where changes did not update on other pages

---

shared/src/containers/ProjectTreeTable/hooks/useFolderRelationships.ts
shared/src/containers/ProjectTreeTable/hooks/useHistory.ts
shared/src/containers/ProjectTreeTable/hooks/useUpdateTableData.ts

- Fixes an issue where if the top folder does not have a explicit value then the inherited value would be null. Now it uses the project attrib value as a fallback.
- Fixes an issue where setting an explicit value on a folder and then pressing undo would only reinstate the value and the inheritance state.

Overview: Inheritance with history fixes

---

shared/src/containers/ProjectTreeTable/context/ClipboardContext.tsx

There could be situations where a attrib value was null because it had not been set on either itself or it's parent. When copying the data it would be null when we should use the attrib default for that type.
The best example was with boolean values.

fix(overview): Copying cells with null values now uses attrib default

---

shared/src/containers/Actions/Actions.tsx
shared/src/containers/Actions/ActionsDropdown/ActionsDropdown.styled.ts
shared/src/containers/Actions/ActionsDropdown/ActionsDropdown.tsx
shared/src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.tsx
shared/src/context/DetailsPanelContext.tsx
src/pages/ProjectListsPage/ProjectListsPage.tsx
src/pages/ProjectOverviewPage/ProjectOverviewPage.tsx

It's really not obvious that when in developer mode the actions are linked to the dev bundle and not the production one. This has caught us out many times before. Now we should the actions button as purple to indicate it is being affected by developer mode being turned on.

Show Actions button as purple when in developer mode

---

src/containers/ProjectMenu/projectMenu.jsx
src/containers/projectList.jsx

The problem goes deeper as the update user preferences query does not also update the user redux state because it's now in the shared folder and does not have access to the redux store.
So this is a bit of a hacky fix and not a long term solution.

Projects: Fix pinning not showing updates

---

src/components/NewEntity/NewEntity.tsx
src/pages/ProjectOverviewPage/ProjectOverviewPage.tsx
src/pages/ProjectOverviewPage/hooks/useExpandAndSelectNewFolders.ts

When Stay Open is checked, the selection will stay on the currently selected folder instead of moving to the newly created folder (behaviour when not checked). This is useful when wanted to create lots of different folders in the same parent folder.

Overview: Enabling stay open for new entity preserves selection

---

shared/src/containers/ProjectTreeTable/ProjectTreeTable.tsx

When using the chevron to open a dropdown now the cell is always selected as well to ensure the cell is updated properly.

Opening overview dropdown now updates correct cell

---

src/pages/SettingsPage/Bundles/BundlesAddonList.jsx

Make it clearer that the dev mode folder for addons needs to be the `/client` folder in the addon.
Came up internally [here](https://discord.com/channels/517362899170230292/1001811244535259207/1395410994565746730) (private).

Bundles: Dev mode: Include `/client` in placeholder path + add tooltip

---

src/pages/SettingsPage/Bundles/BundleDepPackage.jsx

This pull request introduces a small UI improvement to the `BundleDepPackage` component. Now, when displaying the dependency package name, a tooltip is shown with either the package name or "(NONE)" if no package is present.

Add tooltip to dependency package file name

---

src/pages/ProjectManagerPage/Users/mappers.ts

Uses a standard js function for getting the intersection of the set instead of the non-standard .intersection and .difference prototypes.

User access page error

---

shared/src/hooks/useActionTriggers.ts
shared/src/hooks/useCustomProtocolCheck.ts

* Added a message on the custom protocol fail
* On success, we do nothing
* There was a tricky part with Firefox, I accidentally opened the ayon + version. It does nothing. I needed to open the ayon, and it worked. Tested on Mac. 
* Safari works

Add custom protocol fail message

---

shared/src/containers/Feed/components/ActivityDate.tsx
shared/src/containers/Feed/components/ActivityVersions/ActivityVersions.styled.ts
shared/src/containers/Feed/components/ActivityVersions/ActivityVersions.tsx

Feed: New version activity date overflow
Fixed overflow issue in Feed where date text on version activities would push thumbnails out of their container when the feed width was very small. Implemented proper
text truncation and flex layout prioritization to ensure content remains within bounds.
**Layout Behavior:**
- Priority order: Product name (highest) → Thumbnail (fixed) → Date (lowest)
- Space distribution: Text content gets up to 100% width, date limited to 50% when visible
- Overflow handling: All text elements show ellipsis (...) when truncated
- Responsive: Layout adapts gracefully from wide to very narrow feed widths

Feed: New version activity date overflow #1470

---

shared/src/containers/ProjectTreeTable/widgets/EnumWidget.tsx

Fixed enum dropdown to show invalid values as selectable options, allowing users to easily deselect them. Previously, invalid enum values would show with a warning
triangle but weren't available in the dropdown for removal.
- Invalid enum values are now collected into a separate invalidOptions array
- Valid and invalid options are merged into allOptions for the dropdown
- Invalid values maintain their warning styling (error color + warning icon) when displayed in the dropdown
- Users can now click on invalid values in the dropdown to deselect and remove them

Overview: When a enum does not exist we should still show it in dropdown to give option unselect.

---

shared/src/components/DetailsPanelAttributes/DetailsPanelAttributesEditor.tsx
shared/src/containers/Feed/components/CommentInput/CommentInput.styled.ts

This pull request solves the overflow comment section
https://github.com/user-attachments/assets/1bc7a4fa-408c-4d17-9215-13c332996eca

Fix comment section overflow

---

src/containers/TasksProgress/components/FolderBody/FolderBody.styled.ts
src/containers/TasksProgress/components/FolderBody/FolderBody.tsx

When a folder row is both selected and expanded, the Path component (which displays the selected background color) will now be hidden, preventing it from overflowing
behind the thumbnail image.
Fixed the background overflow issue. Here's what I changed:
1. FolderBody.tsx:80 - Added expanded class to the Path component
2. FolderBody.styled.ts:103-107 - Added CSS rule to hide the Path component when expanded
Before:
After fix:

Task Progress: Expanded selected folders glitch

---

src/components/Menu/MenuComponents/MenuItem.jsx
src/components/Menu/MenuComponents/MenuList.jsx
src/containers/ProjectsList/ProjectsList.tsx
src/containers/ProjectsList/hooks/useProjectsListMenuItems.ts
src/pages/ProjectListsPage/components/ListFolderFormDialog/ListFolderForm.tsx
src/pages/ProjectListsPage/components/ListsTable/ListsTableHeader.tsx
src/pages/ProjectListsPage/context/ListsDataContext.tsx
src/pages/ProjectListsPage/context/ListsProvider.tsx
src/pages/ProjectListsPage/util/buildListsTableData.ts
src/pages/ProjectManagerPage/ProjectManagerPageContainer.jsx
src/pages/UserDashboardPage/UserDashboardPage.jsx

You can now toggle to show/hide archived projects and lists in the table dropdown menu.
This state saves for your current session (local storage).

Show archived menu for lists and projects

---

src/pages/ProjectListsPage/components/ListsFiltersDialog/ListsFiltersDialog.tsx
src/pages/ProjectListsPage/components/ListsTable/ListsTableHeader.tsx

Adds dynamic tag-based filtering capability to the Lists Filters Dialog. Users can now filter lists by tags, with the filter options dynamically generated based on tags
present in existing lists.
- Dynamically generates tag filter options from all tags found across lists in listsData
- Integrates with project tag anatomy to display tag colors from projectInfo
- Shows tag counts (number of lists with each tag) and sorts by count (most used first)
- Tag filter only appears when at least one list has tags
- Uses OR operator for tag filtering (shows lists with any of the selected tags)
- Supports custom tag values in the filter

Lists: Filter by tags

---

shared/src/api/generated/views.ts
shared/src/components/ProjectTableSettings/ProjectTableSettings.tsx
shared/src/components/ProjectTableSettings/RowHeightSettings.tsx
shared/src/components/SettingsPanel/SettingsPanel.tsx
shared/src/components/Thumbnail/Thumbnail.styled.ts
shared/src/components/ThumbnailSimple/ThumbnailSimple.tsx
shared/src/containers/ProjectTreeTable/ProjectTreeTable.styled.ts
shared/src/containers/ProjectTreeTable/ProjectTreeTable.tsx
shared/src/containers/ProjectTreeTable/buildTreeTableColumns.tsx
shared/src/containers/ProjectTreeTable/context/ColumnSettingsContext.tsx
shared/src/containers/ProjectTreeTable/context/ColumnSettingsProvider.tsx
shared/src/containers/ProjectTreeTable/hooks/useDynamicRowHeight.ts
shared/src/containers/ProjectTreeTable/widgets/CellWidget.tsx
shared/src/containers/ProjectTreeTable/widgets/EntityNameWidget.tsx
shared/src/containers/ProjectTreeTable/widgets/EnumCellValue.tsx
shared/src/containers/ProjectTreeTable/widgets/ThumbnailWidget.tsx
shared/src/util/columnConfigConverter.ts

Added dynamic thumbnail resizing functionality to the ProjectTreeTable. When users resize the thumbnail column width, thumbnail images now scale to fit the new width while
maintaining their 16:9 aspect ratio, and table rows automatically adjust their height to accommodate the scaled thumbnails.
- **ThumbnailWidget**: Updated to use `width: calc(100% - 8px)` with `aspect-ratio: 1.77` for responsive scaling
- **useDynamicRowHeight hook**: New hook that calculates row height based on thumbnail column width using the formula: `(columnWidth - padding) / aspectRatio + padding`
- **Row virtualizer**: Enhanced to use dynamic `estimateSize` function for variable row heights
- **Table components**: Updated to pass calculated row heights to all table cells and drag handles
**Limitations:**
- All …

Overview: Make thumbnails bigger by increasing the column width

---

src/containers/AddonSettings/AddonSettings.jsx
src/services/addonSettings.js

* In `src/services/addonSettings.js`, the query for addon settings no longer uses the `summary: true` parameter, ensuring that full data is retrieved to support full-text search in settings. This change temporarily increases the payload size but is necessary for search functionality.
* In `src/containers/AddonSettings/AddonSettings.jsx`, a TODO comment was added to the `onUpdateAddonSchema` function, highlighting the need to refactor the logic so that it doesn't rely on the full settings payload from the addon list, which is currently suboptimal for performance.

Fix settings search
